import type { AITool } from "./data"

const placeholderLogo = "/placeholder.svg"

type Pricing = "free" | "freemium" | "subscription" | "pay-per-use" | "one-time" | "enterprise"

function makeTool(t: {
  id: string
  name: string
  description: string
  shortDescription: string
  category: string
  subcategory: string
  pricing: Pricing
  priceRange?: string
  rating: number
  reviews: number
  users: string
  tags: string[]
  features: string[]
  pros: string[]
  cons: string[]
  website?: string
  verified?: boolean
  trending?: boolean
  new?: boolean
  featured?: boolean
}): AITool {
  return {
    ...t,
    logo: placeholderLogo,
    verified: t.verified ?? false,
    trending: t.trending ?? false,
    new: t.new ?? false,
    featured: t.featured ?? false,
  }
}

export const extendedTools: AITool[] = [
  // --- Text & Language ---
  makeTool({ id: "gemini", name: "Google Gemini", description: "Google's multimodal AI for chat, code, and creative tasks. Supports images, long context, and deep integration with Google services.", shortDescription: "Multimodal AI assistant from Google", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free / $20-50/mo", rating: 4.7, reviews: 82000, users: "50M+", tags: ["Chatbot", "Multimodal", "Google", "Coding"], features: ["Multimodal", "Code Generation", "Google Workspace", "Long Context", "Image Understanding"], pros: ["Strong multimodal", "Google integration", "Good free tier"], cons: ["Sometimes verbose", "Region restrictions"], website: "https://gemini.google.com", verified: true, trending: true, featured: true }),
  makeTool({ id: "poe", name: "Poe", description: "Chat with multiple AI models in one place. Access ChatGPT, Claude, Gemini, and dozens of others through a single interface.", shortDescription: "Multi-model AI chat platform", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free / $20/mo", rating: 4.5, reviews: 18000, users: "2M+", tags: ["Chatbot", "Multi-model", "Aggregator"], features: ["Multiple Models", "Bots", "API", "iOS/Android"], pros: ["One app, many models", "Custom bots", "Mobile apps"], cons: ["Pricing can add up", "Some model limits"], website: "https://poe.com", trending: true }),
  makeTool({ id: "character-ai", name: "Character.AI", description: "Chat with AI characters, celebrities, and custom personas. Create and share your own characters.", shortDescription: "AI character chat and roleplay", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free / $10/mo", rating: 4.4, reviews: 120000, users: "20M+", tags: ["Chatbot", "Characters", "Roleplay", "Entertainment"], features: ["Custom Characters", "Group Chats", "Voice", "Community"], pros: ["Huge character library", "Engaging", "Free tier"], cons: ["Content filters", "Sometimes repetitive"], website: "https://character.ai" }),
  makeTool({ id: "mistral-large", name: "Mistral Large", description: "Mistral AI's flagship model for reasoning, code, and multilingual tasks. Strong performance across European languages.", shortDescription: "Powerful European AI model", category: "text-language", subcategory: "Chatbots", pricing: "pay-per-use", priceRange: "From $3/M tokens", rating: 4.6, reviews: 14000, users: "500K+", tags: ["Chatbot", "Multilingual", "API", "Europe"], features: ["128K Context", "Function Calling", "Code", "Multilingual"], pros: ["Strong multilingual", "Good value", "Transparent"], cons: ["Less brand recognition", "API-first"], website: "https://mistral.ai" }),
  makeTool({ id: "groq", name: "Groq", description: "Ultra-fast inference for Llama and Mixtral. Sub-second latency for chat and completion APIs.", shortDescription: "Fastest AI inference API", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free tier / Pay-as-you-go", rating: 4.5, reviews: 8000, users: "200K+", tags: ["API", "Speed", "Llama", "Inference"], features: ["LPU Hardware", "Llama 3", "Mixtral", "Streaming"], pros: ["Extremely fast", "Free tier", "Simple API"], cons: ["Model choice limited", "Rate limits"], website: "https://groq.com" }),
  makeTool({ id: "hugging-chat", name: "Hugging Face Chat", description: "Chat with open models like Llama, Mistral, and others. Free tier with optional Pro for priority access.", shortDescription: "Free chat with open-source models", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free / $9/mo", rating: 4.3, reviews: 22000, users: "5M+", tags: ["Chatbot", "Open Source", "Hugging Face"], features: ["Many Models", "Spaces", "Free", "Community"], pros: ["Truly free", "Model variety", "Developer-friendly"], cons: ["Queue times", "Variable quality"], website: "https://huggingface.co/chat" }),
  makeTool({ id: "writer", name: "Writer", description: "Enterprise AI writing platform for brand-safe content. Trained on your style guide and knowledge base.", shortDescription: "Enterprise AI writing platform", category: "text-language", subcategory: "Content Writing", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 1200, users: "50K+", tags: ["Writing", "Enterprise", "Brand", "Content"], features: ["Brand Voice", "Style Guide", "Knowledge Base", "Palmyra"], pros: ["Brand consistency", "Security", "Governance"], cons: ["Enterprise focus", "Pricing opaque"], website: "https://writer.com" }),
  makeTool({ id: "writesonic", name: "Writesonic", description: "AI writer for blogs, ads, and landing pages. GPT-4 powered with SEO optimization and 100+ templates.", shortDescription: "AI writing for marketing and SEO", category: "text-language", subcategory: "Content Writing", pricing: "freemium", priceRange: "Free / $13-500/mo", rating: 4.4, reviews: 15000, users: "300K+", tags: ["Writing", "SEO", "Marketing", "Blogs"], features: ["Article Writer", "Ads", "Landing Pages", "Paraphrasing"], pros: ["Good SEO tools", "Templates", "Affordable"], cons: ["Quality varies", "Generic feel sometimes"], website: "https://writesonic.com" }),
  makeTool({ id: "rytr", name: "Rytr", description: "Affordable AI writing assistant for blogs, emails, and social. Over 40 use cases and 30+ languages.", shortDescription: "Budget-friendly AI writer", category: "text-language", subcategory: "Content Writing", pricing: "freemium", priceRange: "Free / $9-29/mo", rating: 4.3, reviews: 28000, users: "1M+", tags: ["Writing", "Blogs", "Social", "Multilingual"], features: ["40+ Use Cases", "30+ Languages", "SEO", "Plagiarism Check"], pros: ["Very affordable", "Many use cases", "Clean UI"], cons: ["Output can be generic", "Limited customization"], website: "https://rytr.me" }),
  makeTool({ id: "copywriter-ai", name: "Copywriter AI", description: "Conversion-focused copy for ads, emails, and landing pages. A/B variants and tone control.", shortDescription: "Conversion-focused AI copywriting", category: "text-language", subcategory: "Copywriting", pricing: "subscription", priceRange: "$29-99/mo", rating: 4.4, reviews: 5200, users: "80K+", tags: ["Copywriting", "Ads", "Conversion", "Marketing"], features: ["A/B Variants", "Tone Control", "Templates", "Analytics"], pros: ["Conversion focus", "Easy to use", "Good support"], cons: ["Niche focus", "Subscription only"], website: "https://copywriter.com" }),
  makeTool({ id: "phrasee", name: "Phrasee", description: "AI-powered marketing language optimization. Generate and optimize subject lines, headlines, and ad copy.", shortDescription: "AI marketing language optimization", category: "text-language", subcategory: "Copywriting", pricing: "enterprise", priceRange: "Custom", rating: 4.6, reviews: 400, users: "Enterprise", tags: ["Copywriting", "Marketing", "Optimization", "Enterprise"], features: ["Subject Lines", "Ad Copy", "A/B Testing", "Brand Voice"], pros: ["Proven lift", "Enterprise grade", "Integration"], cons: ["Enterprise only", "Expensive"], website: "https://phrasee.co" }),
  makeTool({ id: "surfer-seo", name: "Surfer SEO", description: "Content editor with NLP guidelines. Optimize articles for search with real-time SERP analysis.", shortDescription: "AI-powered SEO content editor", category: "text-language", subcategory: "SEO", pricing: "subscription", priceRange: "$59-239/mo", rating: 4.5, reviews: 6000, users: "100K+", tags: ["SEO", "Content", "SERP", "NLP"], features: ["Content Editor", "SERP Analyzer", "Keyword Research", "Audit"], pros: ["Data-driven", "Actionable", "Good support"], cons: ["Pricey", "Learning curve"], website: "https://surferseo.com" }),
  makeTool({ id: "jasper-seo", name: "Jasper SEO", description: "SEO-optimized content within Jasper. Keyword integration, meta descriptions, and outline generation.", shortDescription: "SEO content in Jasper workflow", category: "text-language", subcategory: "SEO", pricing: "subscription", priceRange: "Included in Jasper", rating: 4.4, reviews: 4000, users: "100K+", tags: ["SEO", "Content", "Jasper", "Marketing"], features: ["Keyword Integration", "Meta Descriptions", "Outlines", "Templates"], pros: ["Integrated workflow", "Easy", "Brand voice"], cons: ["Requires Jasper", "Extra cost"], website: "https://jasper.ai" }),
  makeTool({ id: "mailmodo", name: "Mailmodo", description: "AI-powered email campaigns with interactive elements. AMP emails, personalization, and automation.", shortDescription: "AI email marketing with interactivity", category: "text-language", subcategory: "Email Writing", pricing: "freemium", priceRange: "Free / $16-999/mo", rating: 4.5, reviews: 1200, users: "20K+", tags: ["Email", "Marketing", "AMP", "Automation"], features: ["AMP Emails", "AI Copy", "Personalization", "Automation"], pros: ["Interactive emails", "AI assist", "Good deliverability"], cons: ["AMP support varies", "Pricing scales"], website: "https://mailmodo.com" }),
  makeTool({ id: "flowrite", name: "Flowrite", description: "AI that turns bullet points into polished emails and messages. Works in Gmail, Outlook, and Slack.", shortDescription: "Turn bullets into polished emails", category: "text-language", subcategory: "Email Writing", pricing: "freemium", priceRange: "Free / $10-20/mo", rating: 4.4, reviews: 3500, users: "150K+", tags: ["Email", "Productivity", "Writing", "Slack"], features: ["Bullet to Email", "Templates", "Chrome Extension", "Slack"], pros: ["Saves time", "Good tone", "Integrations"], cons: ["Template-dependent", "Limited customization"], website: "https://flowrite.com" }),
  makeTool({ id: "deepl", name: "DeepL", description: "Best-in-class neural machine translation. More natural translations than alternatives for 30+ languages.", shortDescription: "Premium AI translation", category: "text-language", subcategory: "Translation", pricing: "freemium", priceRange: "Free / $7-25/mo", rating: 4.8, reviews: 95000, users: "50M+", tags: ["Translation", "Languages", "Writing", "API"], features: ["30+ Languages", "Document Translation", "API", "Glossary"], pros: ["Best translation quality", "Fast", "Privacy-focused"], cons: ["Free limit", "Fewer languages than some"], website: "https://deepl.com" }),
  makeTool({ id: "reword", name: "Reword", description: "AI editor that helps you write better articles. Research, outline, and edit with AI assistance.", shortDescription: "AI editor for articles and research", category: "text-language", subcategory: "Summarization", pricing: "subscription", priceRange: "$20-40/mo", rating: 4.5, reviews: 1800, users: "30K+", tags: ["Writing", "Editor", "Research", "Summarization"], features: ["Research", "Outline", "Edit", "Publish"], pros: ["Writer-focused", "Research built-in", "Clean UX"], cons: ["Article focus", "No free tier"], website: "https://reword.com" }),
  makeTool({ id: "quillbot", name: "QuillBot", description: "Paraphrasing and grammar tool. Rephrase sentences, check grammar, and summarize texts.", shortDescription: "Paraphrasing and grammar assistant", category: "text-language", subcategory: "Paraphrasing", pricing: "freemium", priceRange: "Free / $10-20/mo", rating: 4.5, reviews: 85000, users: "50M+", tags: ["Paraphrasing", "Grammar", "Summarizer", "Writing"], features: ["Paraphrase", "Grammar Check", "Summarizer", "Citation"], pros: ["Popular", "Good free tier", "Extensions"], cons: ["Premium for full power", "Can change meaning"], website: "https://quillbot.com" }),
  makeTool({ id: "you-com", name: "You.com", description: "AI search engine with cited answers. Chat, search, and generate with transparent sources.", shortDescription: "AI search with citations", category: "text-language", subcategory: "Research", pricing: "freemium", priceRange: "Free / $20/mo", rating: 4.4, reviews: 12000, users: "5M+", tags: ["Search", "Research", "Chat", "Citations"], features: ["AI Search", "Chat", "Code", "Apps"], pros: ["Privacy options", "Citations", "Multiple modes"], cons: ["Smaller index", "Less precise than Google"], website: "https://you.com" }),
  makeTool({ id: "consensus", name: "Consensus", description: "Search 200M+ research papers with AI. Get evidence-based answers and citations from peer-reviewed work.", shortDescription: "AI search across research papers", category: "text-language", subcategory: "Research", pricing: "freemium", priceRange: "Free / $9-20/mo", rating: 4.6, reviews: 4200, users: "500K+", tags: ["Research", "Academic", "Citations", "Papers"], features: ["200M+ Papers", "Cite", "Summaries", "Export"], pros: ["Academic focus", "Citeable", "Useful for research"], cons: ["Niche", "Subscription for heavy use"], website: "https://consensus.app" }),

  // --- Image & Design ---
  makeTool({ id: "dall-e-3", name: "DALL·E 3", description: "OpenAI's image generation model. Create detailed images from text, integrated in ChatGPT Plus.", shortDescription: "OpenAI image generation", category: "image-design", subcategory: "Image Generation", pricing: "subscription", priceRange: "ChatGPT Plus", rating: 4.7, reviews: 150000, users: "100M+", tags: ["Images", "Art", "OpenAI", "ChatGPT"], features: ["Text to Image", "In ChatGPT", "Editing", "Styles"], pros: ["High quality", "Integrated", "Easy"], cons: ["Requires Plus", "Usage limits"], website: "https://openai.com", verified: true, trending: true, featured: true }),
  makeTool({ id: "leonardo-ai", name: "Leonardo.AI", description: "AI image generation with game and asset focus. Models, LoRAs, and control for consistent character and style.", shortDescription: "AI art for games and assets", category: "image-design", subcategory: "Image Generation", pricing: "freemium", priceRange: "Free / $12-30/mo", rating: 4.6, reviews: 45000, users: "5M+", tags: ["Images", "Games", "Assets", "Art"], features: ["Image Models", "LoRAs", "Canvas", "API"], pros: ["Game-ready", "Consistent characters", "Good value"], cons: ["Learning curve", "Credit system"], website: "https://leonardo.ai" }),
  makeTool({ id: "ideogram", name: "Ideogram", description: "AI image generator that excels at text in images. Logos, posters, and designs with accurate typography.", shortDescription: "AI images with reliable text", category: "image-design", subcategory: "Image Generation", pricing: "freemium", priceRange: "Free / $8-48/mo", rating: 4.5, reviews: 28000, users: "2M+", tags: ["Images", "Text in Images", "Logos", "Design"], features: ["Text Rendering", "Multiple Models", "Magic Prompt", "Remix"], pros: ["Best text in images", "Clean UI", "Free tier"], cons: ["Newer", "Fewer styles than Midjourney"], website: "https://ideogram.ai" }),
  makeTool({ id: "adobe-firefly", name: "Adobe Firefly", description: "Adobe's generative AI for images, vectors, and edits. Integrated into Creative Cloud with commercial-safe training.", shortDescription: "Adobe generative AI for creatives", category: "image-design", subcategory: "Image Generation", pricing: "subscription", priceRange: "CC / $5 add-on", rating: 4.5, reviews: 35000, users: "20M+", tags: ["Images", "Adobe", "Design", "Vector"], features: ["Text to Image", "Generative Fill", "Vector", "Enterprise"], pros: ["Commercial safe", "CC integration", "Familiar tools"], cons: ["CC required", "Style limits"], website: "https://firefly.adobe.com" }),
  makeTool({ id: "looka", name: "Looka", description: "AI logo maker and brand kit. Design logos, social kits, and brand assets in minutes.", shortDescription: "AI logo and brand design", category: "image-design", subcategory: "Logo Generators", pricing: "one-time", priceRange: "$20-65", rating: 4.5, reviews: 18000, users: "2M+", tags: ["Logo", "Brand", "Design", "AI"], features: ["Logo Maker", "Brand Kit", "Social Pack", "Mockups"], pros: ["Fast", "Affordable", "Complete kit"], cons: ["Templated feel", "Limited revision"], website: "https://looka.com" }),
  makeTool({ id: "tailor-brands", name: "Tailor Brands", description: "AI-powered logo, brand identity, and marketing design. From logo to social and ads.", shortDescription: "AI branding and design suite", category: "image-design", subcategory: "Logo Generators", pricing: "subscription", priceRange: "$4-13/mo", rating: 4.3, reviews: 12000, users: "1M+", tags: ["Logo", "Branding", "Design", "Marketing"], features: ["Logo", "Brand Guide", "Social", "Ads"], pros: ["All-in-one", "Low cost", "Easy"], cons: ["Generic options", "Subscription model"], website: "https://tailorbrands.com" }),
  makeTool({ id: "figma-ai", name: "Figma AI", description: "AI features in Figma for layout, copy, and asset generation. Speed up design workflows.", shortDescription: "AI-assisted design in Figma", category: "image-design", subcategory: "UI/UX Tools", pricing: "subscription", priceRange: "Figma plan", rating: 4.6, reviews: 8000, users: "5M+", tags: ["UI", "UX", "Figma", "Design"], features: ["Layout", "Copy", "Assets", "Search"], pros: ["Native to Figma", "Practical", "Growing"], cons: ["Evolving", "Plan-dependent"], website: "https://figma.com" }),
  makeTool({ id: "uxpin", name: "UXPin", description: "Design and prototype with AI-powered components and merge. Design systems and code in one tool.", shortDescription: "Design, prototype, and code", category: "image-design", subcategory: "UI/UX Tools", pricing: "subscription", priceRange: "$19-69/mo", rating: 4.4, reviews: 3500, users: "200K+", tags: ["UI", "UX", "Prototype", "Design Systems"], features: ["Merge", "Design Systems", "Prototyping", "Code"], pros: ["Code-ready", "Design systems", "Collaboration"], cons: ["Steeper learning", "Pricing"], website: "https://uxpin.com" }),
  makeTool({ id: "luminar", name: "Luminar Neo", description: "AI photo editor with sky replacement, portrait tools, and one-click enhancements.", shortDescription: "AI-powered photo editing", category: "image-design", subcategory: "Photo Enhancement", pricing: "one-time", priceRange: "$59-149", rating: 4.5, reviews: 22000, users: "1M+", tags: ["Photo", "Editing", "AI", "Enhancement"], features: ["Sky AI", "Portrait", "Enhance", "Layers"], pros: ["Powerful", "One-time buy", "Good value"], cons: ["Heavy", "Mac/Windows only"], website: "https://skylum.com/luminar" }),
  makeTool({ id: "topaz-photo", name: "Topaz Photo AI", description: "AI denoising, sharpening, and upscaling. Improve detail and reduce noise in photos.", shortDescription: "AI denoise, sharpen, upscale", category: "image-design", subcategory: "Photo Enhancement", pricing: "one-time", priceRange: "$199", rating: 4.7, reviews: 15000, users: "500K+", tags: ["Photo", "Upscale", "Denoise", "Sharpen"], features: ["Denoise", "Sharpen", "Upscale", "Face Recovery"], pros: ["Best-in-class quality", "Pro use", "Standalone"], cons: ["Expensive", "No subscription"], website: "https://topazlabs.com" }),
  makeTool({ id: "remove-bg", name: "Remove.bg", description: "Instant AI background removal for images and video. API and bulk for designers and developers.", shortDescription: "AI background removal", category: "image-design", subcategory: "Background Removal", pricing: "freemium", priceRange: "Free / $9-299/mo", rating: 4.6, reviews: 85000, users: "20M+", tags: ["Background", "Removal", "Design", "API"], features: ["Photo", "Video", "API", "Plugins"], pros: ["Fast", "Accurate", "API"], cons: ["Free limits", "Video pricing"], website: "https://remove.bg" }),
  makeTool({ id: "photoroom", name: "PhotoRoom", description: "Remove backgrounds, create product shots, and generate marketing visuals with AI.", shortDescription: "Product photos and visuals", category: "image-design", subcategory: "Background Removal", pricing: "freemium", priceRange: "Free / $10-33/mo", rating: 4.5, reviews: 45000, users: "10M+", tags: ["Background", "Product", "Marketing", "Design"], features: ["Background", "Product Shot", "Templates", "API"], pros: ["Product focus", "Templates", "Mobile"], cons: ["Watermark on free", "Credit system"], website: "https://photoroom.com" }),
  makeTool({ id: "heygen", name: "HeyGen", description: "AI video avatars and voiceovers. Create talking-head videos in 40+ languages from script.", shortDescription: "AI video avatars and voiceovers", category: "image-design", subcategory: "AI Avatars", pricing: "subscription", priceRange: "$24-120/mo", rating: 4.6, reviews: 18000, users: "1M+", tags: ["Avatar", "Video", "Voice", "Multilingual"], features: ["Avatars", "Voice Clone", "40+ Languages", "Templates"], pros: ["Natural avatars", "Voice clone", "Simple"], cons: ["Pricey", "Avatar limits"], website: "https://heygen.com" }),
  makeTool({ id: "creatopy", name: "Creatopy", description: "AI ad creative generator. Display, social, and video ads from templates and AI variations.", shortDescription: "AI ad creative generator", category: "image-design", subcategory: "Ad Creatives", pricing: "freemium", priceRange: "Free / $29-99/mo", rating: 4.4, reviews: 2500, users: "100K+", tags: ["Ads", "Creative", "Design", "Marketing"], features: ["Templates", "AI Variations", "Animation", "Collaboration"], pros: ["Ad-focused", "Bulk", "Integrations"], cons: ["Template feel", "Learning curve"], website: "https://creatopy.com" }),

  // --- Video & Audio ---
  makeTool({ id: "pika-labs", name: "Pika Labs", description: "AI video generation from text and images. Create and edit short clips with natural motion.", shortDescription: "AI text and image to video", category: "video-audio", subcategory: "Video Generation", pricing: "freemium", priceRange: "Free / $10-30/mo", rating: 4.5, reviews: 22000, users: "2M+", tags: ["Video", "Generation", "Creative", "AI"], features: ["Text to Video", "Image to Video", "Edit", "Styles"], pros: ["Easy", "Good motion", "Free tier"], cons: ["Short clips", "Quality varies"], website: "https://pika.art" }),
  makeTool({ id: "luma-dream-machine", name: "Luma Dream Machine", description: "AI video generation from text or image. High-quality 5s clips with consistent style.", shortDescription: "AI video from text or image", category: "video-audio", subcategory: "Video Generation", pricing: "pay-per-use", priceRange: "Credits / $30/mo", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Video", "Generation", "Luma", "AI"], features: ["Text to Video", "Image to Video", "API", "Consistent"], pros: ["Quality", "Consistency", "API"], cons: ["Credit-based", "Short only"], website: "https://lumalabs.ai" }),
  makeTool({ id: "kling", name: "Kling AI", description: "AI video generation with strong physics and motion. From Kuaishou, popular in Asia.", shortDescription: "Physics-aware AI video", category: "video-audio", subcategory: "Video Generation", pricing: "freemium", priceRange: "Free / $10-50/mo", rating: 4.6, reviews: 18000, users: "3M+", tags: ["Video", "Generation", "Motion", "AI"], features: ["Text to Video", "Image to Video", "Longer", "Realistic"], pros: ["Realistic motion", "Longer clips", "Good value"], cons: ["Region limits", "Language"], website: "https://klingai.com" }),
  makeTool({ id: "invideo", name: "InVideo AI", description: "AI video creation for ads, social, and marketing. Script to video with stock and AI avatars.", shortDescription: "AI marketing video creator", category: "video-audio", subcategory: "Video Generation", pricing: "freemium", priceRange: "Free / $25-60/mo", rating: 4.4, reviews: 15000, users: "1M+", tags: ["Video", "Marketing", "Ads", "Social"], features: ["Script to Video", "Templates", "Stock", "Avatars"], pros: ["Marketing focus", "Templates", "Easy"], cons: ["Watermark free", "Quality limits"], website: "https://invideo.io" }),
  makeTool({ id: "d-id", name: "D-ID", description: "Create talking avatars from photo and audio. APIs and studio for presentations and content.", shortDescription: "Talking avatars from photo and audio", category: "video-audio", subcategory: "Talking Avatars", pricing: "freemium", priceRange: "Free / $6-300/mo", rating: 4.4, reviews: 8000, users: "500K+", tags: ["Avatar", "Video", "TTS", "API"], features: ["Photo + Audio", "API", "Studio", "Chat"], pros: ["Simple", "API", "Flexible"], cons: ["Avatar quality varies", "Pricing tiers"], website: "https://d-id.com" }),
  makeTool({ id: "capcut", name: "CapCut", description: "Free video editor with AI effects, auto-captions, and trending templates. From ByteDance.", shortDescription: "Free AI video editor", category: "video-audio", subcategory: "Video Editing", pricing: "free", priceRange: "Free", rating: 4.6, reviews: 120000, users: "100M+", tags: ["Video", "Editing", "Free", "Captions"], features: ["Auto Captions", "Effects", "Templates", "Export"], pros: ["Free", "Easy", "Trending tools"], cons: ["Watermark options", "Cloud sync"], website: "https://capcut.com" }),
  makeTool({ id: "veed", name: "VEED.io", description: "Online video editor with AI subtitles, dub, and effects. Record, edit, and publish in browser.", shortDescription: "Online AI video editing", category: "video-audio", subcategory: "Video Editing", pricing: "freemium", priceRange: "Free / $12-70/mo", rating: 4.5, reviews: 25000, users: "3M+", tags: ["Video", "Editing", "Subtitles", "Online"], features: ["Auto Subtitles", "Dub", "Effects", "Screen Record"], pros: ["No install", "Subtitles", "Collaboration"], cons: ["Export limits", "Storage"], website: "https://veed.io" }),
  makeTool({ id: "play-ht", name: "Play.ht", description: "AI voice generator and voice cloning. 900+ voices, 140+ languages, and ultra-realistic TTS.", shortDescription: "AI voice and cloning", category: "video-audio", subcategory: "Voice Cloning", pricing: "freemium", priceRange: "Free / $29-99/mo", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Voice", "TTS", "Cloning", "Audio"], features: ["900+ Voices", "Clone", "140+ Languages", "API"], pros: ["Many voices", "Clone", "API"], cons: ["Clone limits", "Pricing"], website: "https://play.ht" }),
  makeTool({ id: "murf", name: "Murf AI", description: "AI voiceovers for video, e-learning, and ads. Custom voices, multiple languages, and easy editor.", shortDescription: "AI voiceovers for video", category: "video-audio", subcategory: "Text-to-Speech", pricing: "freemium", priceRange: "Free / $19-99/mo", rating: 4.5, reviews: 14000, users: "400K+", tags: ["TTS", "Voiceover", "Video", "E-learning"], features: ["20+ Languages", "Voice Changer", "Editor", "API"], pros: ["Natural", "Editor", "Use cases"], cons: ["Free limit", "Voice choice"], website: "https://murf.ai" }),
  makeTool({ id: "suno", name: "Suno", description: "AI music generation from text. Create songs with vocals and multiple genres.", shortDescription: "AI music with vocals", category: "video-audio", subcategory: "Music Generation", pricing: "freemium", priceRange: "Free / $10-30/mo", rating: 4.6, reviews: 85000, users: "15M+", tags: ["Music", "AI", "Songs", "Creative"], features: ["Text to Song", "Vocals", "Genres", "Extend"], pros: ["Vocals", "Viral", "Easy"], cons: ["Rights", "Quality varies"], website: "https://suno.ai" }),
  makeTool({ id: "udio", name: "Udio", description: "AI music creation from description. Produce full tracks with structure and style control.", shortDescription: "AI music from description", category: "video-audio", subcategory: "Music Generation", pricing: "freemium", priceRange: "Free / $10-30/mo", rating: 4.5, reviews: 32000, users: "2M+", tags: ["Music", "AI", "Creation", "Tracks"], features: ["Description to Music", "Structure", "Styles", "Extend"], pros: ["Full tracks", "Control", "Quality"], cons: ["Newer", "Rights"], website: "https://udio.com" }),
  makeTool({ id: "resemble-ai", name: "Resemble AI", description: "Voice cloning and TTS for games, content, and apps. Low-latency and custom voices.", shortDescription: "Voice clone and TTS", category: "video-audio", subcategory: "Voice Cloning", pricing: "pay-per-use", priceRange: "From $24/mo", rating: 4.5, reviews: 3000, users: "100K+", tags: ["Voice", "Clone", "TTS", "API"], features: ["Clone", "TTS", "API", "Real-time"], pros: ["Clone quality", "API", "Gaming"], cons: ["Pricing", "Ethics"], website: "https://resemble.ai" }),
  makeTool({ id: "tape-it", name: "Tape It", description: "AI podcast editing. Remove filler, enhance audio, and get publish-ready episodes.", shortDescription: "AI podcast editing", category: "video-audio", subcategory: "Podcast Tools", pricing: "subscription", priceRange: "$12-30/mo", rating: 4.5, reviews: 1200, users: "30K+", tags: ["Podcast", "Editing", "AI", "Audio"], features: ["Filler Removal", "Enhance", "Export", "DAW"], pros: ["Podcast-specific", "Fast", "Simple"], cons: ["Niche", "Subscription"], website: "https://tape.it" }),
  makeTool({ id: "adobe-podcast", name: "Adobe Podcast", description: "AI audio enhancer for podcast and voice. Enhance speech and reduce noise in browser.", shortDescription: "AI podcast and voice enhancer", category: "video-audio", subcategory: "Podcast Tools", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 8000, users: "500K+", tags: ["Podcast", "Audio", "Enhance", "Adobe"], features: ["Enhance", "Mic Check", "Transcribe", "Free"], pros: ["Free", "Quality", "No install"], cons: ["Limited", "Upload only"], website: "https://podcast.adobe.com" }),

  // --- Code & Developer ---
  makeTool({ id: "tabnine", name: "Tabnine", description: "AI code completion trained on your codebase. Works in popular IDEs with full-line and full-function.", shortDescription: "AI completion for your codebase", category: "code-developer", subcategory: "Code Generation", pricing: "freemium", priceRange: "Free / $12-39/mo", rating: 4.5, reviews: 12000, users: "1M+", tags: ["Coding", "Completion", "IDE", "AI"], features: ["Full-line", "Codebase", "Many IDEs", "Privacy"], pros: ["Codebase-aware", "Privacy", "Offline"], cons: ["Slower than Copilot", "Model choice"], website: "https://tabnine.com" }),
  makeTool({ id: "codeium", name: "Codeium", description: "Free AI code completion and chat. 70+ languages, 40+ IDEs, and no usage caps on free tier.", shortDescription: "Free AI completion and chat", category: "code-developer", subcategory: "Code Generation", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 15000, users: "2M+", tags: ["Coding", "Free", "Completion", "Chat"], features: ["Completion", "Chat", "70+ Languages", "40+ IDEs"], pros: ["Free", "No caps", "Many IDEs"], cons: ["Newer", "Fewer models"], website: "https://codeium.com" }),
  makeTool({ id: "code-llama", name: "Code Llama", description: "Meta's open code models. Code completion, fill-in, and instruction following for dev workflows.", shortDescription: "Open code models from Meta", category: "code-developer", subcategory: "Code Generation", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 22000, users: "5M+", tags: ["Coding", "Open Source", "Meta", "Llama"], features: ["Completion", "Fill-in", "Instruction", "Sizes"], pros: ["Open", "Good quality", "Self-host"], cons: ["Self-host", "Setup"], website: "https://ai.meta.com/blog/code-llama-large-language-model-coding" }),
  makeTool({ id: "amazon-codewhisperer", name: "Amazon CodeWhisperer", description: "AI code suggestions from AWS. Security scanning, ML suggestions, and IDE plugins.", shortDescription: "AWS AI code suggestions", category: "code-developer", subcategory: "Code Generation", pricing: "freemium", priceRange: "Free / $19/mo", rating: 4.4, reviews: 8000, users: "500K+", tags: ["Coding", "AWS", "Security", "IDE"], features: ["Completion", "Security Scan", "AWS APIs", "IDEs"], pros: ["AWS integration", "Security", "Free tier"], cons: ["AWS bias", "Fewer languages"], website: "https://aws.amazon.com/codewhisperer" }),
  makeTool({ id: "sourcery", name: "Sourcery", description: "AI refactoring and code review for Python. Improve readability, style, and catch bugs.", shortDescription: "AI Python refactoring", category: "code-developer", subcategory: "Bug Fixing", pricing: "freemium", priceRange: "Free / $10-50/mo", rating: 4.5, reviews: 2500, users: "100K+", tags: ["Python", "Refactor", "Review", "Quality"], features: ["Refactor", "Review", "Suggestions", "CI"], pros: ["Python focus", "Actionable", "CI"], cons: ["Python only", "Paid for teams"], website: "https://sourcery.ai" }),
  makeTool({ id: "buzzbot", name: "BuzzBot", description: "AI that fixes bugs and writes tests. Integrates with GitHub and Jira.", shortDescription: "AI bug fixes and tests", category: "code-developer", subcategory: "Bug Fixing", pricing: "subscription", priceRange: "$19-99/mo", rating: 4.3, reviews: 800, users: "20K+", tags: ["Bugs", "Tests", "GitHub", "AI"], features: ["Bug Fix", "Test Gen", "PR", "Jira"], pros: ["Automation", "Integration", "Fast"], cons: ["New", "Limited stacks"], website: "https://buzzbot.io" }),
  makeTool({ id: "mintlify", name: "Mintlify", description: "AI-generated docs from code. Beautiful doc sites, API reference, and guides.", shortDescription: "AI docs from code", category: "code-developer", subcategory: "Code Explanation", pricing: "freemium", priceRange: "Free / $150/mo", rating: 4.6, reviews: 1200, users: "50K+", tags: ["Docs", "API", "Developer", "AI"], features: ["From Code", "API Ref", "Search", "Custom"], pros: ["Beautiful", "Fast", "Maintained"], cons: ["Paid for private", "Customization"], website: "https://mintlify.com" }),
  makeTool({ id: "bolt-new", name: "Bolt.new", description: "Full-stack app builder in browser. AI-assisted React, Node, and deploy in one flow.", shortDescription: "AI full-stack in browser", category: "code-developer", subcategory: "Website Builders", pricing: "freemium", priceRange: "Free / $10-20/mo", rating: 4.4, reviews: 6000, users: "200K+", tags: ["App", "Full-stack", "AI", "Browser"], features: ["AI Build", "React", "Deploy", "Real-time"], pros: ["No install", "Fast", "Deploy"], cons: ["Constraints", "Learning"], website: "https://bolt.new" }),
  makeTool({ id: "v0-dev", name: "v0 by Vercel", description: "Generate UI with AI. React, Tailwind, and shadcn from prompts. Iterate and copy code.", shortDescription: "AI UI generation", category: "code-developer", subcategory: "Website Builders", pricing: "freemium", priceRange: "Free / Pro", rating: 4.6, reviews: 18000, users: "500K+", tags: ["UI", "React", "Tailwind", "Vercel"], features: ["Prompt to UI", "Iterate", "Code", "Components"], pros: ["Quality", "React", "Popular"], cons: ["UI focus", "Vercel ecosystem"], website: "https://v0.dev" }),
  makeTool({ id: "replit-agent", name: "Replit Agent", description: "AI pair programmer in Replit. Generate, edit, and run code from natural language.", shortDescription: "AI coding in Replit", category: "code-developer", subcategory: "Code Generation", pricing: "subscription", priceRange: "Replit subscription", rating: 4.4, reviews: 15000, users: "25M+", tags: ["Coding", "Replit", "Agent", "Cloud"], features: ["Generate", "Edit", "Run", "Deploy"], pros: ["Integrated", "Cloud", "Beginner-friendly"], cons: ["Replit lock-in", "Limits"], website: "https://replit.com" }),
  makeTool({ id: "windsurf", name: "Windsurf", description: "AI-powered IDE by Codeium. Codebase-aware completion, chat, and terminal.", shortDescription: "AI IDE by Codeium", category: "code-developer", subcategory: "Code Generation", pricing: "freemium", priceRange: "Free / $20/mo", rating: 4.4, reviews: 5000, users: "150K+", tags: ["IDE", "Codeium", "AI", "Coding"], features: ["Completion", "Chat", "Terminal", "Codebase"], pros: ["Codeium ecosystem", "Free tier", "Fast"], cons: ["Newer", "Fewer extensions"], website: "https://codeium.com/windsurf" }),
  makeTool({ id: "cursor-shark", name: "Cursor Shark", description: "AI code search and navigation. Find code, understand flows, and refactor across repos.", shortDescription: "AI code search and nav", category: "code-developer", subcategory: "Code Explanation", pricing: "subscription", priceRange: "$15-30/mo", rating: 4.3, reviews: 1200, users: "40K+", tags: ["Codebase", "Search", "Navigation", "AI"], features: ["Semantic Search", "Flow", "Refactor", "Teams"], pros: ["Understanding", "Large repos", "Refactor"], cons: ["Paid", "Setup"], website: "https://cursorshark.com" }),
  makeTool({ id: "codacy", name: "Codacy", description: "Automated code quality and security. AI-powered analysis, PR checks, and standards.", shortDescription: "AI code quality and security", category: "code-developer", subcategory: "AI Testing", pricing: "freemium", priceRange: "Free / $15-50/mo", rating: 4.4, reviews: 2000, users: "100K+", tags: ["Quality", "Security", "PR", "CI"], features: ["Quality", "Security", "PR", "Standards"], pros: ["Automation", "Multi-lang", "Integration"], cons: ["Configuration", "Pricing"], website: "https://codacy.com" }),
  makeTool({ id: "mutable", name: "Mutable AI", description: "AI for rapid product development. Build features, fix bugs, and ship from natural language.", shortDescription: "AI product development", category: "code-developer", subcategory: "No-Code/Low-Code", pricing: "subscription", priceRange: "$30-60/mo", rating: 4.4, reviews: 1800, users: "50K+", tags: ["Product", "Dev", "AI", "Features"], features: ["Features", "Bugs", "Tests", "PR"], pros: ["Product focus", "Fast", "Full-stack"], cons: ["Paid", "Stack limits"], website: "https://mutable.ai" }),
  makeTool({ id: "softr", name: "Softr", description: "No-code apps and portals from Airtable/Sheets. Memberships, forms, and CMS.", shortDescription: "No-code apps from data", category: "code-developer", subcategory: "No-Code/Low-Code", pricing: "freemium", priceRange: "Free / $29-79/mo", rating: 4.5, reviews: 3000, users: "200K+", tags: ["No-code", "Airtable", "Portal", "CMS"], features: ["Templates", "Members", "Forms", "CMS"], pros: ["Data-backed", "Easy", "Templates"], cons: ["Airtable tie", "Customization"], website: "https://softr.io" }),
  makeTool({ id: "retool", name: "Retool", description: "Build internal tools fast. DB, API, and UI components with AI-assisted flows.", shortDescription: "Internal tools builder", category: "code-developer", subcategory: "No-Code/Low-Code", pricing: "freemium", priceRange: "Free / $10-50/user", rating: 4.6, reviews: 2500, users: "500K+", tags: ["Internal", "Tools", "DB", "API"], features: ["Components", "DB", "API", "Workflows"], pros: ["Fast", "Developer-friendly", "Scales"], cons: ["Internal focus", "Learning curve"], website: "https://retool.com" }),
]
