import type { AITool } from "./data"

const logo = "/placeholder.svg"
type P = "free" | "freemium" | "subscription" | "pay-per-use" | "one-time" | "enterprise"

function t(o: {
  id: string
  name: string
  description: string
  shortDescription: string
  category: string
  subcategory: string
  pricing: P
  priceRange?: string
  rating: number
  reviews: number
  users: string
  tags: string[]
  features: string[]
  pros: string[]
  cons: string[]
  website?: string
  verified?: boolean
  trending?: boolean
  new?: boolean
  featured?: boolean
}): AITool {
  return {
    ...o,
    logo,
    verified: o.verified ?? false,
    trending: o.trending ?? false,
    new: o.new ?? false,
    featured: o.featured ?? false,
  }
}

export const moreTools: AITool[] = [
  // --- Text & Language (more) ---
  t({ id: "pi-ai", name: "Pi AI", description: "Personal AI assistant by Inflection. Supportive, conversational, and helpful for daily tasks.", shortDescription: "Personal AI assistant", category: "text-language", subcategory: "Chatbots", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 35000, users: "5M+", tags: ["Chatbot", "Personal", "Conversational"], features: ["Voice", "Web", "Mobile", "Empathetic"], pros: ["Friendly", "Free", "Voice"], cons: ["Less capable", "No code"], website: "https://pi.ai" }),
  t({ id: "meta-ai", name: "Meta AI", description: "AI assistant in Meta apps. Search, chat, and generate in WhatsApp, Instagram, and Facebook.", shortDescription: "AI in Meta apps", category: "text-language", subcategory: "Chatbots", pricing: "free", priceRange: "Free", rating: 4.3, reviews: 120000, users: "100M+", tags: ["Chatbot", "Meta", "Social"], features: ["Search", "Image Gen", "WhatsApp", "IG"], pros: ["Integrated", "Free", "Wide reach"], cons: ["Meta data", "Variable quality"], website: "https://meta.ai" }),
  t({ id: "x-ai-grok", name: "Grok", description: "AI by xAI with real-time X access. Witty, informed by posts, and conversational.", shortDescription: "AI with X access", category: "text-language", subcategory: "Chatbots", pricing: "subscription", priceRange: "X Premium", rating: 4.4, reviews: 28000, users: "2M+", tags: ["Chatbot", "X", "Real-time"], features: ["X Access", "Witty", "Search", "Code"], pros: ["X integration", "Current", "Personality"], cons: ["X required", "Bias"], website: "https://x.ai" }),
  t({ id: "cohere", name: "Cohere", description: "Enterprise NLP and LLM API. Embeddings, generation, and RAG for builders.", shortDescription: "Enterprise NLP API", category: "text-language", subcategory: "Chatbots", pricing: "pay-per-use", priceRange: "From $0.40/M", rating: 4.5, reviews: 4000, users: "100K+", tags: ["API", "NLP", "Enterprise", "RAG"], features: ["Embed", "Generate", "Rerank", "RAG"], pros: ["Enterprise", "RAG", "Privacy"], cons: ["API-first", "Less brand"], website: "https://cohere.com" }),
  t({ id: "openrouter", name: "OpenRouter", description: "Single API for 200+ LLMs. Route to OpenAI, Anthropic, open models, and more.", shortDescription: "Unified LLM API", category: "text-language", subcategory: "Chatbots", pricing: "pay-per-use", priceRange: "Per-model", rating: 4.5, reviews: 3500, users: "80K+", tags: ["API", "Models", "Unified"], features: ["200+ Models", "Fallback", "Usage", "Proxy"], pros: ["One API", "Flexibility", "Fallback"], cons: ["Routing", "Cost tracking"], website: "https://openrouter.ai" }),
  t({ id: "literal-ai", name: "Literal.ai", description: "AI writing for fiction and long-form. Plot, characters, and story assistance.", shortDescription: "AI fiction and long-form", category: "text-language", subcategory: "Content Writing", pricing: "subscription", priceRange: "$10-25/mo", rating: 4.4, reviews: 2200, users: "40K+", tags: ["Writing", "Fiction", "Stories"], features: ["Plot", "Characters", "Editor", "Export"], pros: ["Fiction focus", "Long-form", "Community"], cons: ["Niche", "Quality varies"], website: "https://literal.ai" }),
  t({ id: "novel-ai", name: "NovelAI", description: "AI-assisted storytelling and image generation. Create and extend stories with custom models.", shortDescription: "AI storytelling and images", category: "text-language", subcategory: "Content Writing", pricing: "subscription", priceRange: "$10-25/mo", rating: 4.5, reviews: 18000, users: "500K+", tags: ["Writing", "Stories", "Images", "Custom"], features: ["Story", "Image", "Lorebook", "Styles"], pros: ["Custom", "Privacy", "Active"], cons: ["Anime bias", "Subscription"], website: "https://novelai.net" }),
  t({ id: "scribendi", name: "Scribendi", description: "AI editing and proofreading for academic and professional documents. Human review available.", shortDescription: "AI editing and proofreading", category: "text-language", subcategory: "Content Writing", pricing: "pay-per-use", priceRange: "Per page", rating: 4.5, reviews: 8000, users: "200K+", tags: ["Editing", "Proofreading", "Academic"], features: ["Edit", "Proof", "Human", "Turnaround"], pros: ["Quality", "Human option", "Fast"], cons: ["Cost", "Per-page"], website: "https://scribendi.com" }),
  t({ id: "grammarly-business", name: "Grammarly Business", description: "Team writing assistant. Consistency, tone, and style across org with admin controls.", shortDescription: "Team writing assistant", category: "text-language", subcategory: "Content Writing", pricing: "subscription", priceRange: "$15-25/user/mo", rating: 4.6, reviews: 12000, users: "500K+", tags: ["Writing", "Teams", "Brand", "Grammar"], features: ["Tone", "Style", "Snippets", "Analytics"], pros: ["Teams", "Brand", "Integrations"], cons: ["Pricey", "Over-correction"], website: "https://grammarly.com" }),
  t({ id: "copy-smith", name: "CopySmith", description: "AI copy for e-commerce and ads. Product descriptions, ads, and landing pages.", shortDescription: "AI copy for e-commerce", category: "text-language", subcategory: "Copywriting", pricing: "subscription", priceRange: "$19-99/mo", rating: 4.4, reviews: 4500, users: "100K+", tags: ["Copy", "E-commerce", "Ads", "Product"], features: ["Product Desc", "Ads", "Landing", "Templates"], pros: ["E-com focus", "Bulk", "Integrations"], cons: ["Generic", "Pricing"], website: "https://copysmith.ai" }),
  t({ id: "peppertype", name: "Peppertype", description: "AI content at scale. Blogs, social, ads, and sales copy with workflows.", shortDescription: "AI content at scale", category: "text-language", subcategory: "Copywriting", pricing: "subscription", priceRange: "$35-199/mo", rating: 4.3, reviews: 6000, users: "150K+", tags: ["Content", "Scale", "Workflows", "Marketing"], features: ["50+ Types", "Workflows", "Collaboration", "API"], pros: ["Scale", "Workflows", "Templates"], cons: ["Quality", "Learning"], website: "https://peppertype.ai" }),
  t({ id: "frase", name: "Frase", description: "SEO content and research. Briefs, outlines, and optimization from SERP data.", shortDescription: "SEO content and research", category: "text-language", subcategory: "SEO", pricing: "subscription", priceRange: "$15-115/mo", rating: 4.5, reviews: 5500, users: "80K+", tags: ["SEO", "Content", "Research", "SERP"], features: ["Briefs", "Outline", "Optimize", "Analyze"], pros: ["Research", "Actionable", "Fast"], cons: ["Pricey", "Focused"], website: "https://frase.io" }),
  t({ id: "marketmuse", name: "MarketMuse", description: "AI content strategy and optimization. Topic clusters, gaps, and content scoring.", shortDescription: "AI content strategy", category: "text-language", subcategory: "SEO", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 800, users: "Enterprise", tags: ["SEO", "Strategy", "Content", "Enterprise"], features: ["Topic Clusters", "Gaps", "Scoring", "Recommendations"], pros: ["Strategic", "Data", "Enterprise"], cons: ["Expensive", "Complex"], website: "https://marketmuse.com" }),
  t({ id: "outreach-sales", name: "Outreach Sales AI", description: "AI sales engagement. Email sequences, follow-ups, and pipeline insights.", shortDescription: "AI sales engagement", category: "text-language", subcategory: "Email Writing", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 2000, users: "50K+", tags: ["Sales", "Email", "Engagement", "CRM"], features: ["Sequences", "Templates", "Analytics", "Integrations"], pros: ["Sales focus", "Pipeline", "Scale"], cons: ["Enterprise", "Cost"], website: "https://outreach.io" }),
  t({ id: "lovo-ai", name: "LOVO AI", description: "AI voiceovers and cloning. 500+ voices, 100+ languages, and video dubbing.", shortDescription: "AI voice and dubbing", category: "text-language", subcategory: "Translation", pricing: "freemium", priceRange: "Free / $19-99/mo", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Voice", "TTS", "Dubbing", "Translation"], features: ["500+ Voices", "100+ Lang", "Dubbing", "Clone"], pros: ["Voices", "Dubbing", "Easy"], cons: ["Clone limits", "Pricing"], website: "https://lovo.ai" }),
  t({ id: "summarize-tech", name: "Summarize.tech", description: "AI summaries of YouTube videos. Get key points from long lectures and tutorials.", shortDescription: "YouTube video summaries", category: "text-language", subcategory: "Summarization", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 15000, users: "2M+", tags: ["Summarize", "YouTube", "Video", "Learning"], features: ["YouTube", "Chapters", "Export", "API"], pros: ["Free", "Useful", "Fast"], cons: ["YouTube only", "Accuracy"], website: "https://summarize.tech" }),
  t({ id: "genei", name: "Genei", description: "Summarize and research from PDFs and web. Note-taking and citation for academics.", shortDescription: "Summarize PDFs and web", category: "text-language", subcategory: "Summarization", pricing: "subscription", priceRange: "$8-16/mo", rating: 4.5, reviews: 3500, users: "80K+", tags: ["Summarize", "PDF", "Research", "Notes"], features: ["PDF", "Web", "Notes", "Cite"], pros: ["Research", "PDF", "Clean"], cons: ["Subscription", "Limits"], website: "https://genei.io" }),
  t({ id: "wordtune", name: "Wordtune", description: "AI rewriting and tone. Improve sentences, shorten, expand, and change tone.", shortDescription: "AI rewrite and tone", category: "text-language", subcategory: "Paraphrasing", pricing: "freemium", priceRange: "Free / $10-25/mo", rating: 4.5, reviews: 45000, users: "10M+", tags: ["Rewrite", "Tone", "Writing", "Productivity"], features: ["Rewrite", "Tone", "Shorten", "Expand"], pros: ["Natural", "Chrome", "Quick"], cons: ["Free limit", "Context"], website: "https://wordtune.com" }),
  t({ id: "semantic-scholar", name: "Semantic Scholar", description: "AI-powered academic search. 200M+ papers, citations, and discovery.", shortDescription: "AI academic search", category: "text-language", subcategory: "Research", pricing: "free", priceRange: "Free", rating: 4.6, reviews: 12000, users: "10M+", tags: ["Research", "Academic", "Papers", "Citations"], features: ["200M+ Papers", "Cite", "Recommend", "API"], pros: ["Free", "Academic", "Good UI"], cons: ["Academic only", "Coverage"], website: "https://semanticscholar.org" }),
  t({ id: "elicit", name: "Elicit", description: "Research assistant for literature review. Find, summarize, and synthesize papers.", shortDescription: "AI literature review", category: "text-language", subcategory: "Research", pricing: "freemium", priceRange: "Free / $10-42/mo", rating: 4.6, reviews: 8000, users: "500K+", tags: ["Research", "Papers", "Literature", "Academic"], features: ["Find", "Summarize", "Synthesize", "Cite"], pros: ["Literature focus", "Useful", "Export"], cons: ["Paid for heavy", "Niche"], website: "https://elicit.com" }),

  // --- Image & Design (more) ---
  t({ id: "flux-pro", name: "Flux Pro", description: "Black Forest Labs image model. Fast, versatile, and great for varied styles.", shortDescription: "Fast versatile image model", category: "image-design", subcategory: "Image Generation", pricing: "subscription", priceRange: "$20/mo", rating: 4.6, reviews: 18000, users: "1M+", tags: ["Images", "Flux", "Art", "Fast"], features: ["Text to Image", "Styles", "API", "Fast"], pros: ["Speed", "Quality", "Variety"], cons: ["Subscription", "Newer"], website: "https://blackforestlabs.ai" }),
  t({ id: "replicate-image", name: "Replicate", description: "Run 1000+ AI models via API. Images, video, audio, and open models.", shortDescription: "Run AI models via API", category: "image-design", subcategory: "Image Generation", pricing: "pay-per-use", priceRange: "Per run", rating: 4.6, reviews: 12000, users: "500K+", tags: ["API", "Models", "Images", "Open"], features: ["1000+ Models", "API", "Webhooks", "Scale"], pros: ["Variety", "Pay-per-use", "Open"], cons: ["DIY", "Pricing varies"], website: "https://replicate.com" }),
  t({ id: "sea-art", name: "SeaArt", description: "AI art platform with models, LoRAs, and community. Good for anime and illustration.", shortDescription: "AI art with community", category: "image-design", subcategory: "Image Generation", pricing: "freemium", priceRange: "Free / $10-30/mo", rating: 4.4, reviews: 15000, users: "1M+", tags: ["Art", "Anime", "LoRA", "Community"], features: ["Models", "LoRA", "Train", "Share"], pros: ["Community", "Anime", "Free"], cons: ["Quality varies", "Credits"], website: "https://seaart.ai" }),
  t({ id: "brandmark", name: "Brandmark", description: "AI logo and brand identity. Generate logos, colors, and brand guidelines.", shortDescription: "AI logo and brand", category: "image-design", subcategory: "Logo Generators", pricing: "one-time", priceRange: "$25-175", rating: 4.4, reviews: 8000, users: "300K+", tags: ["Logo", "Brand", "AI", "Design"], features: ["Logo", "Colors", "Fonts", "Guidelines"], pros: ["Complete", "Fast", "Affordable"], cons: ["Generic", "Limited edits"], website: "https://brandmark.io" }),
  t({ id: "canva-magic", name: "Canva Magic Studio", description: "AI design tools in Canva. Magic Write, Eraser, Design, and more.", shortDescription: "AI design in Canva", category: "image-design", subcategory: "UI/UX Tools", pricing: "subscription", priceRange: "Pro $13/mo", rating: 4.6, reviews: 95000, users: "150M+", tags: ["Design", "Canva", "AI", "Templates"], features: ["Magic Write", "Eraser", "Design", "Resize"], pros: ["Integrated", "Easy", "Huge library"], cons: ["Pro for AI", "Export limits"], website: "https://canva.com" }),
  t({ id: "visily", name: "Visily", description: "AI wireframes and prototypes. From sketch or screenshot to high-fidelity UI.", shortDescription: "AI wireframes and prototypes", category: "image-design", subcategory: "UI/UX Tools", pricing: "freemium", priceRange: "Free / $19-49/mo", rating: 4.4, reviews: 2500, users: "80K+", tags: ["Wireframe", "Prototype", "UI", "AI"], features: ["Sketch to UI", "Screenshot", "Templates", "Export"], pros: ["Fast", "Screenshot import", "Collaboration"], cons: ["Learning", "Fidelity"], website: "https://visily.ai" }),
  t({ id: "lets-enhance", name: "LetsEnhance", description: "AI image upscaler and enhancer. Increase resolution and fix quality.", shortDescription: "AI upscale and enhance", category: "image-design", subcategory: "Photo Enhancement", pricing: "freemium", priceRange: "Free / $9-39/mo", rating: 4.5, reviews: 22000, users: "2M+", tags: ["Upscale", "Enhance", "Photo", "AI"], features: ["Upscale", "Denoise", "Enhance", "Batch"], pros: ["Quality", "Batch", "API"], cons: ["Credits", "Limits"], website: "https://letsenhance.io" }),
  t({ id: "clipdrop", name: "ClipDrop", description: "AI image tools: background remove, relight, upscale, and object replace.", shortDescription: "AI image tools suite", category: "image-design", subcategory: "Background Removal", pricing: "freemium", priceRange: "Free / $9-99/mo", rating: 4.5, reviews: 35000, users: "5M+", tags: ["Image", "Background", "Upscale", "Tools"], features: ["Background", "Relight", "Upscale", "Replace"], pros: ["Suite", "Quality", "API"], cons: ["Credit system", "Pricing"], website: "https://clipdrop.co" }),
  t({ id: "sadtalker", name: "SadTalker", description: "Talking head from single image and audio. Open model, self-host or API.", shortDescription: "Talking head from image", category: "image-design", subcategory: "AI Avatars", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 5000, users: "200K+", tags: ["Avatar", "Talking", "Open", "Video"], features: ["Image + Audio", "Open", "Custom", "API"], pros: ["Open", "Flexible", "Free"], cons: ["Tech", "Quality"], website: "https://github.com/OpenTalker/SadTalker" }),
  t({ id: "predis-ai", name: "Predis.ai", description: "AI social media content and creatives. Posts, carousels, and ads from prompts.", shortDescription: "AI social creatives", category: "image-design", subcategory: "Ad Creatives", pricing: "freemium", priceRange: "Free / $29-99/mo", rating: 4.4, reviews: 1800, users: "50K+", tags: ["Social", "Ads", "Creatives", "AI"], features: ["Posts", "Carousels", "Ads", "Calendar"], pros: ["Social focus", "Templates", "Easy"], cons: ["Generic", "Limits"], website: "https://predis.ai" }),

  // --- Video & Audio (more) ---
  t({ id: "minimax-video", name: "MiniMax Video", description: "AI video and voice from MiniMax. Text-to-video and TTS with strong quality.", shortDescription: "AI video and voice", category: "video-audio", subcategory: "Video Generation", pricing: "pay-per-use", priceRange: "Credits", rating: 4.5, reviews: 8000, users: "500K+", tags: ["Video", "Voice", "AI", "China"], features: ["Text to Video", "TTS", "Avatar", "API"], pros: ["Quality", "Voice", "API"], cons: ["Region", "Credits"], website: "https://minimax.chat" }),
  t({ id: "wan-video", name: "Wan Video", description: "AI short video creation. Clips for social and ads from templates.", shortDescription: "AI short video", category: "video-audio", subcategory: "Video Generation", pricing: "subscription", priceRange: "$20-60/mo", rating: 4.3, reviews: 3000, users: "100K+", tags: ["Video", "Short", "Social", "Ads"], features: ["Templates", "AI", "Music", "Export"], pros: ["Quick", "Templates", "Social"], cons: ["Generic", "Limits"], website: "https://wanvideo.ai" }),
  t({ id: "creatok", name: "Creatok", description: "AI avatar videos for training and marketing. Custom avatars and 140+ languages.", shortDescription: "AI avatar videos", category: "video-audio", subcategory: "Talking Avatars", pricing: "subscription", priceRange: "$24-120/mo", rating: 4.4, reviews: 2000, users: "50K+", tags: ["Avatar", "Video", "Training", "Marketing"], features: ["Avatars", "140+ Lang", "Templates", "API"], pros: ["Languages", "Templates", "Simple"], cons: ["Pricey", "Avatar limits"], website: "https://creatok.ai" }),
  t({ id: "flexclip", name: "FlexClip", description: "Online video maker with AI. Script to video, voiceover, and subtitles.", shortDescription: "AI online video maker", category: "video-audio", subcategory: "Video Editing", pricing: "freemium", priceRange: "Free / $10-20/mo", rating: 4.4, reviews: 12000, users: "500K+", tags: ["Video", "Online", "AI", "Editing"], features: ["Script to Video", "Voiceover", "Subtitles", "Templates"], pros: ["Easy", "Templates", "No install"], cons: ["Watermark", "Export"], website: "https://flexclip.com" }),
  t({ id: "speechify", name: "Speechify", description: "Text-to-speech for reading. Listen to articles, PDFs, and books.", shortDescription: "TTS for reading", category: "video-audio", subcategory: "Text-to-Speech", pricing: "freemium", priceRange: "Free / $139/yr", rating: 4.6, reviews: 85000, users: "25M+", tags: ["TTS", "Reading", "Accessibility", "Productivity"], features: ["Natural Voices", "Chrome", "Mobile", "Speed"], pros: ["Natural", "Popular", "Accessibility"], cons: ["Premium for best", "Price"], website: "https://speechify.com" }),
  t({ id: "soundraw", name: "Soundraw", description: "AI music for content. Create tracks, adjust mood and length, royalty-free.", shortDescription: "AI royalty-free music", category: "video-audio", subcategory: "Music Generation", pricing: "subscription", priceRange: "$17-31/mo", rating: 4.5, reviews: 8000, users: "200K+", tags: ["Music", "Royalty-free", "Content", "AI"], features: ["Create", "Mood", "Length", "Download"], pros: ["Royalty-free", "Custom", "Easy"], cons: ["Subscription", "Style limits"], website: "https://soundraw.io" }),
  t({ id: "aiva", name: "AIVA", description: "AI composer for film, games, and ads. Create orchestral and electronic tracks.", shortDescription: "AI music composer", category: "video-audio", subcategory: "Music Generation", pricing: "freemium", priceRange: "Free / $11-39/mo", rating: 4.5, reviews: 12000, users: "300K+", tags: ["Music", "Compose", "Film", "Games"], features: ["Compose", "Styles", "Export", "Custom"], pros: ["Quality", "Film focus", "API"], cons: ["Learning", "Rights"], website: "https://aiva.ai" }),
  t({ id: "riverside", name: "Riverside", description: "Record podcast and video. Separate tracks, transcription, and AI clips.", shortDescription: "Podcast and video recording", category: "video-audio", subcategory: "Podcast Tools", pricing: "subscription", priceRange: "$15-24/mo", rating: 4.6, reviews: 8000, users: "100K+", tags: ["Podcast", "Record", "Video", "Transcription"], features: ["Record", "Tracks", "Transcribe", "Clips"], pros: ["Quality", "Transcription", "Clips"], cons: ["Price", "Setup"], website: "https://riverside.fm" }),
  t({ id: "descript-podcast", name: "Descript Podcast", description: "Podcast editing in Descript. Transcription, filler removal, and overdub.", shortDescription: "Podcast in Descript", category: "video-audio", subcategory: "Podcast Tools", pricing: "subscription", priceRange: "Descript $12-24/mo", rating: 4.6, reviews: 15000, users: "1M+", tags: ["Podcast", "Edit", "Transcribe", "Descript"], features: ["Transcribe", "Filler", "Overdub", "Publish"], pros: ["Edit as text", "Overdub", "Easy"], cons: ["Descript only", "Export"], website: "https://descript.com" }),

  // --- Code & Developer (more) ---
  t({ id: "codestral", name: "Codestral", description: "Mistral's code model. Completion, fill-in, and instruction for dev workflows.", shortDescription: "Mistral code model", category: "code-developer", subcategory: "Code Generation", pricing: "pay-per-use", priceRange: "API", rating: 4.5, reviews: 5000, users: "150K+", tags: ["Code", "Mistral", "API", "Completion"], features: ["Completion", "Fill", "Instruction", "128K"], pros: ["Quality", "Multilingual", "API"], cons: ["API only", "Newer"], website: "https://mistral.ai" }),
  t({ id: "continue-dev", name: "Continue", description: "Open-source AI coding assistant. Use any model in VS Code with codebase context.", shortDescription: "Open-source AI coding", category: "code-developer", subcategory: "Code Generation", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Coding", "Open", "VS Code", "Models"], features: ["Any Model", "Codebase", "Chat", "Edit"], pros: ["Open", "Any model", "Free"], cons: ["BYOK", "Setup"], website: "https://continue.dev" }),
  t({ id: "codegeex", name: "CodeGeeX", description: "AI code completion and translation. 20+ languages, VS Code and JetBrains.", shortDescription: "AI completion and translation", category: "code-developer", subcategory: "Code Generation", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 8000, users: "400K+", tags: ["Completion", "Translation", "IDE", "AI"], features: ["Complete", "Translate", "Chat", "IDEs"], pros: ["Free", "Translate", "Good"], cons: ["English bias", "Quality"], website: "https://codegeex.ai" }),
  t({ id: "coderabbit", name: "CodeRabbit", description: "AI code review for pull requests. Automated feedback and security checks.", shortDescription: "AI PR code review", category: "code-developer", subcategory: "Bug Fixing", pricing: "freemium", priceRange: "Free / $12-99/mo", rating: 4.5, reviews: 2500, users: "80K+", tags: ["Review", "PR", "GitHub", "AI"], features: ["Review", "Security", "Suggest", "Integrate"], pros: ["Automated", "Actionable", "Security"], cons: ["PR only", "Noise"], website: "https://coderabbit.ai" }),
  t({ id: "bubble", name: "Bubble", description: "No-code web app builder. Database, workflows, and responsive UI without code.", shortDescription: "No-code web apps", category: "code-developer", subcategory: "No-Code/Low-Code", pricing: "freemium", priceRange: "Free / $29-529/mo", rating: 4.5, reviews: 15000, users: "3M+", tags: ["No-code", "Web", "Apps", "Database"], features: ["Visual", "DB", "Workflows", "Plugins"], pros: ["Powerful", "Scale", "Community"], cons: ["Learning", "Cost at scale"], website: "https://bubble.io" }),
  t({ id: "webflow-ai", name: "Webflow", description: "Design and launch responsive sites. CMS, e-commerce, and no-code.", shortDescription: "No-code web design", category: "code-developer", subcategory: "Website Builders", pricing: "subscription", priceRange: "$14-212/mo", rating: 4.6, reviews: 12000, users: "500K+", tags: ["Web", "Design", "CMS", "No-code"], features: ["Visual", "CMS", "E-com", "Hosting"], pros: ["Design control", "CMS", "Export"], cons: ["Price", "Learning"], website: "https://webflow.com" }),
  t({ id: "teleport", name: "Teleport HQ", description: "Design to code. Create UI, get React/Vue/HTML and deploy.", shortDescription: "Design to code", category: "code-developer", subcategory: "Website Builders", pricing: "freemium", priceRange: "Free / $19-49/mo", rating: 4.4, reviews: 3500, users: "150K+", tags: ["Design", "Code", "React", "Vue"], features: ["Design", "Code", "Export", "Collaborate"], pros: ["Design to code", "Clean", "Integrations"], cons: ["Complex UI", "Pricing"], website: "https://teleporthq.io" }),
  t({ id: "postman-ai", name: "Postman AI", description: "AI in Postman for API docs, tests, and debugging. Generate requests and assertions.", shortDescription: "AI for APIs in Postman", category: "code-developer", subcategory: "API Generators", pricing: "subscription", priceRange: "Postman plan", rating: 4.5, reviews: 6000, users: "30M+", tags: ["API", "Postman", "Testing", "AI"], features: ["Docs", "Tests", "Debug", "Generate"], pros: ["Integrated", "Useful", "Familiar"], cons: ["Postman only", "Paid"], website: "https://postman.com" }),
  t({ id: "panda-gpt", name: "Panda GPT", description: "AI code review and refactor. Improve quality and security across repos.", shortDescription: "AI code review", category: "code-developer", subcategory: "AI Testing", pricing: "subscription", priceRange: "$15-50/mo", rating: 4.3, reviews: 1200, users: "30K+", tags: ["Review", "Quality", "Security", "AI"], features: ["Review", "Refactor", "Security", "CI"], pros: ["Automation", "Multi-lang", "CI"], cons: ["Paid", "Setup"], website: "https://pandagpt.io" }),

  // --- Business & Marketing ---
  t({ id: "adcreative-ai", name: "AdCreative.ai", description: "AI ad creatives for Facebook, Google, and LinkedIn. Generate and A/B test creatives.", shortDescription: "AI ad creatives", category: "business-marketing", subcategory: "Ads Generation", pricing: "subscription", priceRange: "$29-149/mo", rating: 4.5, reviews: 8000, users: "200K+", tags: ["Ads", "Creative", "Facebook", "Google"], features: ["Generate", "A/B", "Templates", "Analytics"], pros: ["Ad focus", "A/B", "Easy"], cons: ["Subscription", "Limits"], website: "https://adcreative.ai" }),
  t({ id: "creatives-ai", name: "Creatives.ai", description: "AI marketing creatives. Ads, social, and email from prompts.", shortDescription: "AI marketing creatives", category: "business-marketing", subcategory: "Ads Generation", pricing: "subscription", priceRange: "$19-99/mo", rating: 4.4, reviews: 3500, users: "80K+", tags: ["Ads", "Creative", "Marketing", "AI"], features: ["Ads", "Social", "Email", "Templates"], pros: ["All-in-one", "Templates", "Fast"], cons: ["Generic", "Pricing"], website: "https://creatives.ai" }),
  t({ id: "phrasee-ads", name: "Phrasee Ads", description: "AI ad copy optimization. Generate and optimize headlines and body copy.", shortDescription: "AI ad copy", category: "business-marketing", subcategory: "Ads Generation", pricing: "enterprise", priceRange: "Custom", rating: 4.6, reviews: 600, users: "Enterprise", tags: ["Ads", "Copy", "Optimization", "Enterprise"], features: ["Headlines", "Body", "A/B", "Brand"], pros: ["Proven", "Enterprise", "Integration"], cons: ["Enterprise", "Cost"], website: "https://phrasee.co" }),
  t({ id: "hubspot-ai", name: "HubSpot AI", description: "AI across HubSpot. Content, ads, sales, and service with GPT-powered assist.", shortDescription: "AI in HubSpot", category: "business-marketing", subcategory: "CRM AI", pricing: "subscription", priceRange: "HubSpot plan", rating: 4.6, reviews: 25000, users: "200K+", tags: ["CRM", "Marketing", "Sales", "AI"], features: ["Content", "Ads", "Sales", "Service"], pros: ["Integrated", "All-in-one", "Mature"], cons: ["HubSpot only", "Cost"], website: "https://hubspot.com" }),
  t({ id: "salesforce-einstein", name: "Salesforce Einstein", description: "AI for Salesforce. Predictions, recommendations, and automation across CRM.", shortDescription: "AI for Salesforce", category: "business-marketing", subcategory: "CRM AI", pricing: "subscription", priceRange: "Salesforce plan", rating: 4.5, reviews: 18000, users: "150K+", tags: ["CRM", "Salesforce", "AI", "Predictions"], features: ["Predict", "Recommend", "Automate", "Insights"], pros: ["Native", "Powerful", "Scale"], cons: ["Complex", "Pricey"], website: "https://salesforce.com" }),
  t({ id: "pipedrive-ai", name: "Pipedrive AI", description: "AI sales assistant in Pipedrive. Lead scoring, follow-ups, and insights.", shortDescription: "AI sales in Pipedrive", category: "business-marketing", subcategory: "CRM AI", pricing: "subscription", priceRange: "Pipedrive plan", rating: 4.5, reviews: 12000, users: "100K+", tags: ["CRM", "Sales", "Pipedrive", "AI"], features: ["Scoring", "Follow-up", "Insights", "Automate"], pros: ["Sales focus", "Easy", "Integrations"], cons: ["Pipedrive only", "Add-on"], website: "https://pipedrive.com" }),
  t({ id: "apollo-ai", name: "Apollo.io", description: "AI-powered sales intelligence. Find leads, enrich data, and automate outreach.", shortDescription: "AI sales intelligence", category: "business-marketing", subcategory: "Lead Generation", pricing: "freemium", priceRange: "Free / $49-149/mo", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Leads", "Sales", "Enrichment", "Outreach"], features: ["Find", "Enrich", "Sequence", "Integrate"], pros: ["Data", "Integrations", "Scale"], cons: ["Pricey", "Accuracy"], website: "https://apollo.io" }),
  t({ id: "clay", name: "Clay", description: "AI data enrichment and lead gen. Combine sources, personalize outreach.", shortDescription: "AI lead gen and enrich", category: "business-marketing", subcategory: "Lead Generation", pricing: "subscription", priceRange: "$149-349/mo", rating: 4.6, reviews: 3500, users: "80K+", tags: ["Leads", "Enrichment", "Personalization", "AI"], features: ["Enrich", "Personalize", "Workflows", "Integrate"], pros: ["Flexible", "Powerful", "Data"], cons: ["Pricey", "Learning"], website: "https://clay.com" }),
  t({ id: "instantly", name: "Instantly", description: "AI cold email at scale. Unlimited accounts, warming, and analytics.", shortDescription: "AI cold email", category: "business-marketing", subcategory: "Lead Generation", pricing: "subscription", priceRange: "$30-97/mo", rating: 4.5, reviews: 6000, users: "150K+", tags: ["Cold Email", "Outreach", "Scale", "AI"], features: ["Unlimited", "Warming", "Analytics", "Integrate"], pros: ["Scale", "Warming", "Analytics"], cons: ["Deliverability", "Support"], website: "https://instantly.ai" }),
  t({ id: "similarweb", name: "Similarweb", description: "Digital market intelligence. Traffic, competitors, and trends with AI insights.", shortDescription: "Market intelligence", category: "business-marketing", subcategory: "Market Research", pricing: "subscription", priceRange: "Custom", rating: 4.5, reviews: 8000, users: "100K+", tags: ["Market", "Traffic", "Competitors", "Research"], features: ["Traffic", "Competitors", "Trends", "API"], pros: ["Data", "Coverage", "Insights"], cons: ["Pricey", "Accuracy"], website: "https://similarweb.com" }),
  t({ id: "exploding-topics", name: "Exploding Topics", description: "Discover trending topics and emerging markets. AI-curated trend reports.", shortDescription: "Trending topics discovery", category: "business-marketing", subcategory: "Market Research", pricing: "subscription", priceRange: "$39-249/mo", rating: 4.5, reviews: 2500, users: "80K+", tags: ["Trends", "Research", "Markets", "AI"], features: ["Trends", "Reports", "Alerts", "Export"], pros: ["Early", "Curated", "Useful"], cons: ["Niche", "Subscription"], website: "https://explodingtopics.com" }),
  t({ id: "gong", name: "Gong", description: "Revenue intelligence. AI insights from sales calls, emails, and meetings.", shortDescription: "Revenue intelligence", category: "business-marketing", subcategory: "Sales AI", pricing: "enterprise", priceRange: "Custom", rating: 4.6, reviews: 5000, users: "80K+", tags: ["Sales", "Revenue", "Calls", "AI"], features: ["Calls", "Emails", "Deals", "Coaching"], pros: ["Actionable", "Scale", "Integrations"], cons: ["Enterprise", "Cost"], website: "https://gong.io" }),
  t({ id: "chorus", name: "Chorus", description: "Conversation intelligence for sales. Call recording, transcription, and coaching.", shortDescription: "Sales conversation intelligence", category: "business-marketing", subcategory: "Sales AI", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 3000, users: "50K+", tags: ["Sales", "Calls", "Coaching", "AI"], features: ["Record", "Transcribe", "Insights", "Coaching"], pros: ["Quality", "Coaching", "Integrate"], cons: ["Enterprise", "Price"], website: "https://chorus.io" }),
  t({ id: "mixpanel", name: "Mixpanel", description: "Product analytics with AI. Funnels, retention, and predictions.", shortDescription: "Product analytics AI", category: "business-marketing", subcategory: "Analytics", pricing: "freemium", priceRange: "Free / $25-833/mo", rating: 4.5, reviews: 2500, users: "30K+", tags: ["Analytics", "Product", "Funnels", "AI"], features: ["Funnels", "Retention", "Predict", "Cohorts"], pros: ["Product focus", "Powerful", "API"], cons: ["Learning", "Cost at scale"], website: "https://mixpanel.com" }),
  t({ id: "amplitude", name: "Amplitude", description: "Product and growth analytics. AI-driven insights and experimentation.", shortDescription: "Product and growth analytics", category: "business-marketing", subcategory: "Analytics", pricing: "freemium", priceRange: "Free / Custom", rating: 4.6, reviews: 2000, users: "30K+", tags: ["Analytics", "Product", "Growth", "AI"], features: ["Analytics", "Experiment", "Predict", "Integrate"], pros: ["Growth", "Experiment", "Scale"], cons: ["Complex", "Pricing"], website: "https://amplitude.com" }),
  t({ id: "price2b", name: "Price2B", description: "AI dynamic pricing. Optimize e-commerce prices from demand and competitors.", shortDescription: "AI dynamic pricing", category: "business-marketing", subcategory: "Pricing Tools", pricing: "subscription", priceRange: "Custom", rating: 4.4, reviews: 800, users: "20K+", tags: ["Pricing", "E-commerce", "Dynamic", "AI"], features: ["Dynamic", "Competitors", "Rules", "API"], pros: ["Automation", "Data", "Integrate"], cons: ["Niche", "Cost"], website: "https://price2b.com" }),
  t({ id: "wisemargin", name: "WiseMargin", description: "AI margin and pricing optimization. Wholesale and retail pricing insights.", shortDescription: "AI margin and pricing", category: "business-marketing", subcategory: "Pricing Tools", pricing: "subscription", priceRange: "$49-199/mo", rating: 4.3, reviews: 500, users: "10K+", tags: ["Pricing", "Margin", "Retail", "AI"], features: ["Margin", "Pricing", "Reports", "Integrate"], pros: ["Margin focus", "Useful", "Easy"], cons: ["Niche", "Newer"], website: "https://wisemargin.com" }),

  // --- Automation & Agents ---
  t({ id: "make", name: "Make", description: "Visual automation. Connect apps, build workflows, and run AI scenarios.", shortDescription: "Visual automation", category: "automation-agents", subcategory: "Workflow Automation", pricing: "freemium", priceRange: "Free / $9-299/mo", rating: 4.6, reviews: 15000, users: "1M+", tags: ["Automation", "Workflows", "Integrations", "AI"], features: ["Visual", "1000+ Apps", "AI", "Scenarios"], pros: ["Powerful", "Visual", "Flexible"], cons: ["Learning", "Cost at scale"], website: "https://make.com" }),
  t({ id: "n8n", name: "n8n", description: "Self-hosted workflow automation. 400+ nodes, AI, and fair-code.", shortDescription: "Self-hosted workflows", category: "automation-agents", subcategory: "Workflow Automation", pricing: "freemium", priceRange: "Free / $20-50/mo", rating: 4.7, reviews: 12000, users: "500K+", tags: ["Automation", "Self-host", "Workflows", "Open"], features: ["400+ Nodes", "AI", "Self-host", "Cloud"], pros: ["Self-host", "Fair-code", "Flexible"], cons: ["Setup", "Support"], website: "https://n8n.io" }),
  t({ id: "pipedream", name: "Pipedream", description: "Connect APIs and build workflows. 1000+ integrations, code steps, and AI.", shortDescription: "API workflows", category: "automation-agents", subcategory: "Workflow Automation", pricing: "freemium", priceRange: "Free / $19-99/mo", rating: 4.5, reviews: 8000, users: "300K+", tags: ["API", "Workflows", "Integrations", "AI"], features: ["1000+ Apps", "Code", "AI", "Triggers"], pros: ["Developer-friendly", "API", "Flexible"], cons: ["Technical", "Pricing"], website: "https://pipedream.com" }),
  t({ id: "workflow-automation", name: "Workflow Automation", description: "AI workflow builder. Natural language to automation across 500+ apps.", shortDescription: "AI workflow builder", category: "automation-agents", subcategory: "Workflow Automation", pricing: "subscription", priceRange: "$29-99/mo", rating: 4.4, reviews: 2500, users: "80K+", tags: ["Workflow", "AI", "Automation", "Apps"], features: ["NL to Flow", "500+ Apps", "Templates", "Monitor"], pros: ["NL", "Easy", "Apps"], cons: ["Limits", "Support"], website: "https://workflowautomation.ai" }),
  t({ id: "agentflow", name: "Agentflow", description: "AI agents for workflows. Autonomous tasks, research, and multi-step automation.", shortDescription: "AI agents for workflows", category: "automation-agents", subcategory: "AI Agents", pricing: "subscription", priceRange: "$49-199/mo", rating: 4.4, reviews: 1200, users: "30K+", tags: ["Agents", "AI", "Workflows", "Autonomous"], features: ["Agents", "Multi-step", "Research", "Integrate"], pros: ["Autonomous", "Flexible", "Powerful"], cons: ["New", "Cost"], website: "https://agentflow.ai" }),
  t({ id: "langchain", name: "LangChain", description: "Framework for LLM applications. Chains, agents, and tools for builders.", shortDescription: "LLM apps framework", category: "automation-agents", subcategory: "AI Agents", pricing: "free", priceRange: "Free", rating: 4.6, reviews: 35000, users: "1M+", tags: ["Agents", "LLM", "Framework", "Python"], features: ["Chains", "Agents", "Tools", "Ecosystem"], pros: ["Popular", "Flexible", "Ecosystem"], cons: ["Technical", "Complexity"], website: "https://langchain.com" }),
  t({ id: "crewai", name: "CrewAI", description: "Orchestrate AI agents. Role-based agents that collaborate on tasks.", shortDescription: "AI agent orchestration", category: "automation-agents", subcategory: "AI Agents", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 8000, users: "200K+", tags: ["Agents", "Orchestration", "AI", "Python"], features: ["Agents", "Roles", "Tasks", "Collaborate"], pros: ["Roles", "Collaboration", "Open"], cons: ["Technical", "Newer"], website: "https://crewai.com" }),
  t({ id: "ui-path", name: "UiPath", description: "RPA and process automation. Bots, AI, and enterprise scale.", shortDescription: "RPA and process automation", category: "automation-agents", subcategory: "RPA Tools", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 8000, users: "100K+", tags: ["RPA", "Automation", "Bots", "Enterprise"], features: ["Bots", "AI", "Orchestrator", "Integrate"], pros: ["Enterprise", "Scale", "Support"], cons: ["Cost", "Complex"], website: "https://uipath.com" }),
  t({ id: "automation-anywhere", name: "Automation Anywhere", description: "Cloud RPA with AI. Bots, IQ Bot, and discovery.", shortDescription: "Cloud RPA with AI", category: "automation-agents", subcategory: "RPA Tools", pricing: "enterprise", priceRange: "Custom", rating: 4.4, reviews: 5000, users: "80K+", tags: ["RPA", "Cloud", "AI", "Bots"], features: ["Bots", "IQ Bot", "Discovery", "Cloud"], pros: ["Cloud", "AI", "Scale"], cons: ["Enterprise", "Cost"], website: "https://automationanywhere.com" }),
  t({ id: "motion", name: "Motion", description: "AI calendar and task manager. Schedule meetings, prioritize work, and block focus.", shortDescription: "AI calendar and tasks", category: "automation-agents", subcategory: "Task Managers", pricing: "subscription", priceRange: "$19-34/mo", rating: 4.5, reviews: 6000, users: "150K+", tags: ["Calendar", "Tasks", "AI", "Productivity"], features: ["Schedule", "Prioritize", "Focus", "Integrate"], pros: ["Smart scheduling", "Tasks", "Integrations"], cons: ["Pricey", "Learning"], website: "https://usemotion.com" }),
  t({ id: "reclaim-ai", name: "Reclaim.ai", description: "AI calendar defense. Block focus, habits, and tasks automatically.", shortDescription: "AI calendar defense", category: "automation-agents", subcategory: "Scheduling", pricing: "freemium", priceRange: "Free / $8-12/mo", rating: 4.5, reviews: 3500, users: "100K+", tags: ["Calendar", "Scheduling", "AI", "Focus"], features: ["Focus", "Habits", "Tasks", "Slack"], pros: ["Defense", "Habits", "Slack"], cons: ["Calendar only", "Limits"], website: "https://reclaim.ai" }),
  t({ id: "clockwise", name: "Clockwise", description: "AI calendar optimization. Reduce meetings, protect focus, and sync teams.", shortDescription: "AI calendar optimization", category: "automation-agents", subcategory: "Scheduling", pricing: "freemium", priceRange: "Free / $7-12/user", rating: 4.5, reviews: 2500, users: "80K+", tags: ["Calendar", "Meetings", "Focus", "AI"], features: ["Optimize", "Focus", "Sync", "Integrate"], pros: ["Focus", "Teams", "Easy"], cons: ["Calendar only", "Paid for teams"], website: "https://clockwise.com" }),
  t({ id: "todoist", name: "Todoist", description: "Task manager with AI suggestions. Prioritize, schedule, and natural language add.", shortDescription: "Tasks with AI", category: "automation-agents", subcategory: "Task Managers", pricing: "freemium", priceRange: "Free / $4-6/mo", rating: 4.6, reviews: 45000, users: "30M+", tags: ["Tasks", "Productivity", "AI", "Cross-platform"], features: ["Tasks", "NL Add", "Prioritize", "Integrate"], pros: ["Popular", "Clean", "Integrations"], cons: ["AI limited", "Premium"], website: "https://todoist.com" }),
  t({ id: "notion-calendar", name: "Notion Calendar", description: "Calendar by Notion. Scheduling, views, and connection to Notion.", shortDescription: "Calendar by Notion", category: "automation-agents", subcategory: "Scheduling", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 8000, users: "5M+", tags: ["Calendar", "Notion", "Scheduling", "Productivity"], features: ["Calendar", "Views", "Notion", "Integrate"], pros: ["Notion", "Free", "Clean"], cons: ["Notion tie", "Basic"], website: "https://notion.so/calendar" }),

  // --- Data & Analytics ---
  t({ id: "tableau-pulse", name: "Tableau Pulse", description: "AI-powered analytics in Tableau. Natural language questions and insights.", shortDescription: "AI analytics in Tableau", category: "data-analytics", subcategory: "Data Analysis", pricing: "subscription", priceRange: "Tableau plan", rating: 4.6, reviews: 12000, users: "100K+", tags: ["Analytics", "BI", "Tableau", "AI"], features: ["NL Questions", "Insights", "Viz", "Explain"], pros: ["Powerful", "NL", "Enterprise"], cons: ["Pricey", "Learning"], website: "https://tableau.com" }),
  t({ id: "power-bi-copilot", name: "Power BI Copilot", description: "AI in Power BI. Summarize, generate reports, and ask questions in natural language.", shortDescription: "AI in Power BI", category: "data-analytics", subcategory: "Data Analysis", pricing: "subscription", priceRange: "Power BI plan", rating: 4.5, reviews: 15000, users: "200K+", tags: ["BI", "Power BI", "AI", "Reports"], features: ["Summarize", "Reports", "NL", "Insights"], pros: ["Microsoft", "NL", "Integrate"], cons: ["Power BI only", "Licensing"], website: "https://powerbi.microsoft.com" }),
  t({ id: "thoughtspot", name: "ThoughtSpot", description: "Search-driven analytics. Ask questions in natural language, get answers and viz.", shortDescription: "Search-driven analytics", category: "data-analytics", subcategory: "Data Analysis", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 1500, users: "50K+", tags: ["Analytics", "Search", "NL", "BI"], features: ["Search", "NL", "Viz", "Explain"], pros: ["Search", "Easy", "Scale"], cons: ["Enterprise", "Cost"], website: "https://thoughtspot.com" }),
  t({ id: "sisense", name: "Sisense", description: "Embedded analytics and AI. Build dashboards, infuse apps, and natural language.", shortDescription: "Embedded analytics AI", category: "data-analytics", subcategory: "AI Dashboards", pricing: "enterprise", priceRange: "Custom", rating: 4.4, reviews: 1200, users: "40K+", tags: ["Analytics", "Embedded", "Dashboards", "AI"], features: ["Embed", "Dashboards", "NL", "API"], pros: ["Embedded", "Flexible", "Scale"], cons: ["Enterprise", "Complex"], website: "https://sisense.com" }),
  t({ id: "metabase", name: "Metabase", description: "Open-source BI and dashboards. Ask questions, create viz, and share.", shortDescription: "Open BI and dashboards", category: "data-analytics", subcategory: "AI Dashboards", pricing: "freemium", priceRange: "Free / $85-500/mo", rating: 4.5, reviews: 8000, users: "50K+", tags: ["BI", "Open", "Dashboards", "SQL"], features: ["Questions", "Viz", "Alerts", "Embed"], pros: ["Open", "Easy", "Self-host"], cons: ["Scale", "Support"], website: "https://metabase.com" }),
  t({ id: "hex", name: "Hex", description: "Data workspace with AI. SQL, Python, viz, and collaborative notebooks.", shortDescription: "Data workspace AI", category: "data-analytics", subcategory: "Data Analysis", pricing: "freemium", priceRange: "Free / $50-99/user", rating: 4.6, reviews: 1200, users: "30K+", tags: ["Data", "SQL", "Python", "Notebooks"], features: ["SQL", "Python", "Viz", "Collaborate"], pros: ["Collaborative", "Flexible", "AI"], cons: ["Pricey", "Learning"], website: "https://hex.tech" }),
  t({ id: "alteryx-ai", name: "Alteryx AI", description: "Analytics automation with AI. Prep, blend, and predict without code.", shortDescription: "Analytics automation AI", category: "data-analytics", subcategory: "Predictive Analytics", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 3000, users: "80K+", tags: ["Analytics", "Automation", "Predict", "No-code"], features: ["Prep", "Blend", "Predict", "Deploy"], pros: ["No-code", "Powerful", "Scale"], cons: ["Cost", "Learning"], website: "https://alteryx.com" }),
  t({ id: "dataiku", name: "Dataiku", description: "AI and ML platform. From prep to deploy, collaborative and enterprise-ready.", shortDescription: "AI and ML platform", category: "data-analytics", subcategory: "Predictive Analytics", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 800, users: "20K+", tags: ["ML", "Data", "Platform", "Enterprise"], features: ["Prep", "ML", "Deploy", "Collaborate"], pros: ["End-to-end", "Collaborative", "Enterprise"], cons: ["Complex", "Cost"], website: "https://dataiku.com" }),
  t({ id: "domo", name: "Domo", description: "Cloud BI with AI. Dashboards, alerts, and natural language insights.", shortDescription: "Cloud BI with AI", category: "data-analytics", subcategory: "AI Dashboards", pricing: "enterprise", priceRange: "Custom", rating: 4.4, reviews: 2000, users: "30K+", tags: ["BI", "Cloud", "Dashboards", "AI"], features: ["Dashboards", "Alerts", "NL", "Integrate"], pros: ["Cloud", "Integrations", "Mobile"], cons: ["Cost", "Learning"], website: "https://domo.com" }),
  t({ id: "finmodel-ai", name: "FinModel AI", description: "AI financial modeling. Forecasts, scenarios, and variance analysis.", shortDescription: "AI financial modeling", category: "data-analytics", subcategory: "Financial Modeling", pricing: "subscription", priceRange: "Custom", rating: 4.4, reviews: 600, users: "15K+", tags: ["Finance", "Modeling", "Forecast", "AI"], features: ["Forecast", "Scenarios", "Variance", "Integrate"], pros: ["Finance focus", "Automation", "Useful"], cons: ["Niche", "Cost"], website: "https://finmodel.ai" }),
  t({ id: "quantexa", name: "Quantexa", description: "Decision intelligence for risk and compliance. Entity resolution, network, and AI.", shortDescription: "Risk and compliance AI", category: "data-analytics", subcategory: "Risk Analysis", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 400, users: "Enterprise", tags: ["Risk", "Compliance", "Entity", "AI"], features: ["Entity", "Network", "Risk", "Comply"], pros: ["Risk focus", "Scale", "Enterprise"], cons: ["Enterprise", "Complex"], website: "https://quantexa.com" }),

  // --- Education & Learning ---
  t({ id: "khan-migo", name: "Khanmigo", description: "AI tutor by Khan Academy. Math, science, writing, and personalized practice.", shortDescription: "AI tutor by Khan Academy", category: "education-learning", subcategory: "AI Tutors", pricing: "subscription", priceRange: "$9/mo", rating: 4.6, reviews: 25000, users: "500K+", tags: ["Tutor", "Khan", "Math", "Education"], features: ["Tutor", "Practice", "Explain", "Personalize"], pros: ["Khan quality", "Affordable", "Structured"], cons: ["Subscription", "Subjects"], website: "https://khanacademy.org" }),
  t({ id: "quizlet-plus", name: "Quizlet Plus", description: "AI-powered study. Flashcards, practice tests, and Q-Chat tutor.", shortDescription: "AI study and tutor", category: "education-learning", subcategory: "AI Tutors", pricing: "subscription", priceRange: "$8-36/yr", rating: 4.6, reviews: 120000, users: "60M+", tags: ["Study", "Flashcards", "Tutor", "Education"], features: ["Flashcards", "Q-Chat", "Tests", "Export"], pros: ["Popular", "Tutor", "Mobile"], cons: ["Plus for AI", "Quality varies"], website: "https://quizlet.com" }),
  t({ id: "socratic", name: "Socratic", description: "AI homework help by Google. Photo of problem, get step-by-step explanations.", shortDescription: "AI homework help", category: "education-learning", subcategory: "AI Tutors", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 85000, users: "20M+", tags: ["Homework", "Google", "Explain", "Education"], features: ["Photo", "Explain", "Steps", "Subjects"], pros: ["Free", "Photo", "Google"], cons: ["Homework only", "Accuracy"], website: "https://socratic.org" }),
  t({ id: "course-hero-ai", name: "Course Hero AI", description: "AI study help. Explanations, Q&A, and tutor for course materials.", shortDescription: "AI study help", category: "education-learning", subcategory: "AI Tutors", pricing: "subscription", priceRange: "$10-20/mo", rating: 4.4, reviews: 15000, users: "500K+", tags: ["Study", "Tutor", "Course", "Education"], features: ["Explain", "Q&A", "Tutor", "Materials"], pros: ["Course focus", "Materials", "Tutor"], cons: ["Subscription", "Coverage"], website: "https://coursehero.com" }),
  t({ id: "teachable-ai", name: "Teachable AI", description: "AI course creation. Outlines, quiz gen, and content assist for instructors.", shortDescription: "AI course creation", category: "education-learning", subcategory: "Course Generators", pricing: "subscription", priceRange: "$39-119/mo", rating: 4.5, reviews: 8000, users: "100K+", tags: ["Courses", "Create", "AI", "Education"], features: ["Outline", "Quiz", "Content", "Sell"], pros: ["Easy", "All-in-one", "Sell"], cons: ["Teachable only", "Fees"], website: "https://teachable.com" }),
  t({ id: "tutorai", name: "TutorAI", description: "AI course generator. Create courses from topic or URL with structure and quizzes.", shortDescription: "AI course generator", category: "education-learning", subcategory: "Course Generators", pricing: "subscription", priceRange: "$20-50/mo", rating: 4.4, reviews: 2500, users: "50K+", tags: ["Courses", "Generator", "AI", "Education"], features: ["From Topic", "From URL", "Quizzes", "Export"], pros: ["Fast", "Flexible", "Quizzes"], cons: ["Quality", "Limits"], website: "https://tutorai.me" }),
  t({ id: "busuu", name: "Busuu", description: "AI language learning. Lessons, speech recognition, and personalized plans.", shortDescription: "AI language learning", category: "education-learning", subcategory: "Language Learning", pricing: "freemium", priceRange: "Free / $7-13/mo", rating: 4.5, reviews: 45000, users: "100M+", tags: ["Language", "Learning", "AI", "Speech"], features: ["Lessons", "Speech", "Plans", "Community"], pros: ["Structured", "Speech", "Community"], cons: ["Premium", "Content"], website: "https://busuu.com" }),
  t({ id: "rosetta-stone", name: "Rosetta Stone", description: "Language learning with TruAccent. Immersive, speech recognition, and tutoring.", shortDescription: "Immersive language learning", category: "education-learning", subcategory: "Language Learning", pricing: "subscription", priceRange: "$12-299", rating: 4.4, reviews: 55000, users: "50M+", tags: ["Language", "Immersive", "Speech", "Tutor"], features: ["Immersive", "TruAccent", "Tutor", "Phrasebook"], pros: ["Immersive", "Pronunciation", "Structured"], cons: ["Pricey", "Pace"], website: "https://rosettastone.com" }),
  t({ id: "codecademy-ai", name: "Codecademy", description: "Learn to code with AI assist. Courses, practice, and hints.", shortDescription: "Learn to code with AI", category: "education-learning", subcategory: "Coding Education", pricing: "freemium", priceRange: "Free / $18-25/mo", rating: 4.5, reviews: 35000, users: "50M+", tags: ["Coding", "Learn", "Courses", "AI"], features: ["Courses", "Practice", "Hints", "Projects"], pros: ["Popular", "Hands-on", "AI"], cons: ["Subscription", "Depth"], website: "https://codecademy.com" }),
  t({ id: "brilliant", name: "Brilliant", description: "Math and science with interactive lessons. Problem-solving and AI-assisted explain.", shortDescription: "Math and science learning", category: "education-learning", subcategory: "Coding Education", pricing: "subscription", priceRange: "$13-25/mo", rating: 4.6, reviews: 22000, users: "10M+", tags: ["Math", "Science", "Interactive", "AI"], features: ["Interactive", "Problem-solving", "Explain", "Paths"], pros: ["Engaging", "Depth", "Visual"], cons: ["Subscription", "Scope"], website: "https://brilliant.org" }),
  t({ id: "knowji", name: "Knowji", description: "Vocabulary and exam prep. Spaced repetition, audio, and AI adapt.", shortDescription: "Vocabulary and exam prep", category: "education-learning", subcategory: "Exam Prep", pricing: "freemium", priceRange: "Free / $5-10/mo", rating: 4.5, reviews: 12000, users: "500K+", tags: ["Vocabulary", "Exam", "SAT", "Spaced"], features: ["Spaced", "Audio", "Adapt", "Exam"], pros: ["Exam focus", "Spaced", "Audio"], cons: ["Niche", "Premium"], website: "https://knowji.com" }),
  t({ id: "examity", name: "Examity", description: "AI proctoring and exam integrity. Identity verification, monitoring, and analytics.", shortDescription: "AI proctoring", category: "education-learning", subcategory: "Exam Prep", pricing: "enterprise", priceRange: "Custom", rating: 4.4, reviews: 1500, users: "500K+", tags: ["Proctoring", "Exam", "Integrity", "AI"], features: ["Verify", "Monitor", "Analytics", "Integrate"], pros: ["Integrity", "Scale", "Enterprise"], cons: ["Enterprise", "Privacy"], website: "https://examity.com" }),

  // --- Health, Finance & Legal ---
  t({ id: "ada-health", name: "Ada Health", description: "AI health assessment. Symptom checker, triage, and care guidance.", shortDescription: "AI health assessment", category: "health-finance-legal", subcategory: "Health Assistants", pricing: "freemium", priceRange: "Free / B2B", rating: 4.5, reviews: 8000, users: "12M+", tags: ["Health", "Symptom", "Triage", "AI"], features: ["Symptom", "Triage", "Care", "Integrate"], pros: ["Useful", "Multilingual", "B2B"], cons: ["Not diagnosis", "Disclaimer"], website: "https://ada.com" }),
  t({ id: "babylon-health", name: "Babylon Health", description: "AI-powered healthcare. Triage, GP at Hand, and digital health tools.", shortDescription: "AI healthcare", category: "health-finance-legal", subcategory: "Health Assistants", pricing: "subscription", priceRange: "By provider", rating: 4.3, reviews: 15000, users: "24M+", tags: ["Health", "GP", "Triage", "Digital"], features: ["Triage", "GP", "Digital", "Integrate"], pros: ["Access", "Digital", "Scale"], cons: ["Region", "Controversy"], website: "https://babylonhealth.com" }),
  t({ id: "whoop", name: "Whoop", description: "AI fitness and recovery. Strain, sleep, and HRV with personalized insights.", shortDescription: "AI fitness and recovery", category: "health-finance-legal", subcategory: "Fitness AI", pricing: "subscription", priceRange: "$20-30/mo", rating: 4.5, reviews: 45000, users: "1M+", tags: ["Fitness", "Recovery", "Sleep", "Wearable"], features: ["Strain", "Sleep", "HRV", "Recovery"], pros: ["Recovery", "Sleep", "Data"], cons: ["Subscription", "Hardware"], website: "https://whoop.com" }),
  t({ id: "freeletics", name: "Freeletics", description: "AI fitness coaching. Personalized workouts, form feedback, and nutrition.", shortDescription: "AI fitness coaching", category: "health-finance-legal", subcategory: "Fitness AI", pricing: "subscription", priceRange: "$15-35/mo", rating: 4.5, reviews: 35000, users: "50M+", tags: ["Fitness", "Coaching", "Workouts", "AI"], features: ["Workouts", "Form", "Nutrition", "Coach"], pros: ["Personalized", "No equipment", "App"], cons: ["Subscription", "Intensity"], website: "https://freeletics.com" }),
  t({ id: "betterment", name: "Betterment", description: "AI investing and advice. Goal-based portfolios, tax-loss harvesting, and planning.", shortDescription: "AI investing", category: "health-finance-legal", subcategory: "Finance Advisors", pricing: "subscription", priceRange: "0.25-0.5% AUM", rating: 4.5, reviews: 25000, users: "700K+", tags: ["Investing", "Robo", "Advice", "AI"], features: ["Portfolios", "Tax-loss", "Goals", "Advice"], pros: ["Easy", "Tax", "Goals"], cons: ["Fees", "Limited"], website: "https://betterment.com" }),
  t({ id: "wealthfront", name: "Wealthfront", description: "Automated investing and planning. Portfolios, path, and high-yield cash.", shortDescription: "Automated investing", category: "health-finance-legal", subcategory: "Finance Advisors", pricing: "freemium", priceRange: "0.25% AUM", rating: 4.5, reviews: 15000, users: "500K+", tags: ["Investing", "Robo", "Planning", "AI"], features: ["Portfolios", "Path", "Cash", "Borrow"], pros: ["Planning", "Cash", "Automation"], cons: ["AUM", "Limited"], website: "https://wealthfront.com" }),
  t({ id: "mint-budget", name: "Mint", description: "Budget and track spending. AI insights, goals, and credit monitoring.", shortDescription: "Budget and spending", category: "health-finance-legal", subcategory: "Budgeting AI", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 150000, users: "30M+", tags: ["Budget", "Spending", "Goals", "Credit"], features: ["Track", "Goals", "Credit", "Insights"], pros: ["Free", "Popular", "All-in-one"], cons: ["Ads", "Intuit"], website: "https://mint.intuit.com" }),
  t({ id: "ynab", name: "YNAB", description: "Budgeting with rules. Plan, track, and improve with AI-powered insights.", shortDescription: "Rule-based budgeting", category: "health-finance-legal", subcategory: "Budgeting AI", pricing: "subscription", priceRange: "$15/mo", rating: 4.7, reviews: 35000, users: "1M+", tags: ["Budget", "Rules", "Plan", "AI"], features: ["Rules", "Track", "Goals", "Reports"], pros: ["Method", "Support", "Integrations"], cons: ["Paid", "Learning"], website: "https://ynab.com" }),
  t({ id: "harvey-ai", name: "Harvey AI", description: "AI for law firms. Research, drafting, and analysis with enterprise security.", shortDescription: "AI for law firms", category: "health-finance-legal", subcategory: "Legal AI", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 800, users: "20K+", tags: ["Legal", "Research", "Draft", "AI"], features: ["Research", "Draft", "Analyze", "Secure"], pros: ["Legal focus", "Enterprise", "Quality"], cons: ["Enterprise", "Cost"], website: "https://harvey.ai" }),
  t({ id: "case-text", name: "CaseText", description: "AI legal research and drafting. CoCounsel by CaseText for lawyers.", shortDescription: "AI legal research", category: "health-finance-legal", subcategory: "Legal AI", pricing: "subscription", priceRange: "Custom", rating: 4.5, reviews: 2000, users: "50K+", tags: ["Legal", "Research", "Draft", "CoCounsel"], features: ["Research", "Draft", "Review", "Cite"], pros: ["Quality", "CoCounsel", "Integrate"], cons: ["Paid", "Legal only"], website: "https://casetext.com" }),
  t({ id: "logicgate", name: "LogicGate", description: "GRC and compliance automation. Risk, audit, and policy with AI assist.", shortDescription: "GRC and compliance", category: "health-finance-legal", subcategory: "Compliance", pricing: "enterprise", priceRange: "Custom", rating: 4.4, reviews: 500, users: "Enterprise", tags: ["Compliance", "GRC", "Risk", "AI"], features: ["Risk", "Audit", "Policy", "Automate"], pros: ["GRC", "Automation", "Scale"], cons: ["Enterprise", "Complex"], website: "https://logicgate.com" }),
  t({ id: "one-trust", name: "OneTrust", description: "Privacy and compliance platform. Assessment, automation, and AI insights.", shortDescription: "Privacy and compliance", category: "health-finance-legal", subcategory: "Compliance", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 1200, users: "14K+", tags: ["Privacy", "Compliance", "GDPR", "AI"], features: ["Assess", "Automate", "Insights", "Integrate"], pros: ["Privacy", "Scale", "Trust"], cons: ["Enterprise", "Cost"], website: "https://onetrust.com" }),

  // --- Industry-Specific ---
  t({ id: "octane-ai", name: "Octane AI", description: "AI for Shopify. Quiz, product recs, and personalized experiences.", shortDescription: "AI for Shopify", category: "industry-specific", subcategory: "E-commerce AI", pricing: "subscription", priceRange: "$50-500/mo", rating: 4.6, reviews: 1200, users: "20K+", tags: ["E-commerce", "Shopify", "Quiz", "Personalization"], features: ["Quiz", "Recs", "SMS", "Integrate"], pros: ["Shopify", "Quiz", "Convert"], cons: ["Shopify", "Price"], website: "https://octaneai.com" }),
  t({ id: "nosto", name: "Nosto", description: "AI commerce experience. Product recs, search, and personalization.", shortDescription: "AI commerce experience", category: "industry-specific", subcategory: "E-commerce AI", pricing: "subscription", priceRange: "Custom", rating: 4.5, reviews: 500, users: "5K+", tags: ["E-commerce", "Recs", "Search", "Personalization"], features: ["Recs", "Search", "Personalize", "Analytics"], pros: ["Recs", "Search", "Scale"], cons: ["Enterprise", "Cost"], website: "https://nosto.com" }),
  t({ id: "zillow-ai", name: "Zillow AI", description: "AI home valuation and search. Zestimate, recs, and insights.", shortDescription: "AI home valuation", category: "industry-specific", subcategory: "Real Estate AI", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 150000, users: "50M+", tags: ["Real Estate", "Valuation", "Search", "AI"], features: ["Zestimate", "Search", "Recs", "Insights"], pros: ["Data", "Free", "Popular"], cons: ["Accuracy", "US focus"], website: "https://zillow.com" }),
  t({ id: "reonomy", name: "Reonomy", description: "Commercial real estate intelligence. Properties, ownership, and AI insights.", shortDescription: "CRE intelligence", category: "industry-specific", subcategory: "Real Estate AI", pricing: "subscription", priceRange: "Custom", rating: 4.5, reviews: 800, users: "50K+", tags: ["CRE", "Data", "Intelligence", "AI"], features: ["Properties", "Ownership", "Search", "Integrate"], pros: ["CRE focus", "Data", "Useful"], cons: ["B2B", "Cost"], website: "https://reonomy.com" }),
  t({ id: "greenhouse", name: "Greenhouse", description: "Hiring software with AI. Structure, bias reduc, and candidate insights.", shortDescription: "AI hiring", category: "industry-specific", subcategory: "HR & Hiring", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 4000, users: "7K+", tags: ["Hiring", "HR", "Recruiting", "AI"], features: ["Structure", "Bias", "Insights", "Integrate"], pros: ["Structure", "Bias", "Scale"], cons: ["Enterprise", "Cost"], website: "https://greenhouse.io" }),
  t({ id: "lever", name: "Lever", description: "Talent acquisition with AI. Sourcing, pipeline, and diversity insights.", shortDescription: "Talent acquisition AI", category: "industry-specific", subcategory: "HR & Hiring", pricing: "enterprise", priceRange: "Custom", rating: 4.5, reviews: 2500, users: "5K+", tags: ["Hiring", "Talent", "Sourcing", "AI"], features: ["Sourcing", "Pipeline", "Diversity", "Integrate"], pros: ["Talent", "Pipeline", "Diversity"], cons: ["Enterprise", "Price"], website: "https://lever.co" }),
  t({ id: "intercom-finely", name: "Intercom Fin", description: "AI customer support. Answer, triage, and resolve with Fin bot.", shortDescription: "AI customer support", category: "industry-specific", subcategory: "Customer Support", pricing: "subscription", priceRange: "Intercom plan", rating: 4.5, reviews: 8000, users: "30K+", tags: ["Support", "Chatbot", "Intercom", "AI"], features: ["Answer", "Triage", "Resolve", "Integrate"], pros: ["Integrated", "Quality", "Scale"], cons: ["Intercom", "Cost"], website: "https://intercom.com" }),
  t({ id: "zendesk-answer-bot", name: "Zendesk Answer Bot", description: "AI support bot. Deflect, resolve, and hand off to agents.", shortDescription: "AI support bot", category: "industry-specific", subcategory: "Customer Support", pricing: "subscription", priceRange: "Zendesk plan", rating: 4.5, reviews: 12000, users: "100K+", tags: ["Support", "Bot", "Zendesk", "AI"], features: ["Deflect", "Resolve", "Handoff", "Integrate"], pros: ["Zendesk", "Deflection", "Scale"], cons: ["Zendesk", "Setup"], website: "https://zendesk.com" }),
  t({ id: "inworld", name: "Inworld", description: "AI characters for games. NPCs with personality, memory, and voice.", shortDescription: "AI game characters", category: "industry-specific", subcategory: "Gaming AI", pricing: "pay-per-use", priceRange: "API", rating: 4.5, reviews: 1500, users: "50K+", tags: ["Gaming", "NPC", "Characters", "AI"], features: ["NPCs", "Personality", "Memory", "Voice"], pros: ["Game focus", "Quality", "API"], cons: ["API", "Cost"], website: "https://inworld.ai" }),
  t({ id: "ludo-ai", name: "Ludo AI", description: "AI game design. Generate concepts, mechanics, and content from prompts.", shortDescription: "AI game design", category: "industry-specific", subcategory: "Gaming AI", pricing: "subscription", priceRange: "$10-30/mo", rating: 4.4, reviews: 2000, users: "80K+", tags: ["Gaming", "Design", "Generate", "AI"], features: ["Concepts", "Mechanics", "Content", "Export"], pros: ["Ideation", "Fast", "Useful"], cons: ["Indie", "Quality"], website: "https://ludo.ai" }),
  t({ id: "creatomate", name: "Creatomate", description: "API video creation. Templates, automation, and AI for developers.", shortDescription: "API video creation", category: "industry-specific", subcategory: "Creator Tools", pricing: "subscription", priceRange: "$29-99/mo", rating: 4.5, reviews: 800, users: "20K+", tags: ["Video", "API", "Templates", "Creator"], features: ["API", "Templates", "Automate", "Render"], pros: ["API", "Automation", "Scale"], cons: ["Technical", "Niche"], website: "https://creatomate.com" }),
  t({ id: "descript-creator", name: "Descript Creator", description: "Podcast and video for creators. Edit, overdub, and publish.", shortDescription: "Creator podcast and video", category: "industry-specific", subcategory: "Creator Tools", pricing: "subscription", priceRange: "Descript $12-24/mo", rating: 4.6, reviews: 15000, users: "1M+", tags: ["Creator", "Podcast", "Video", "Edit"], features: ["Edit", "Overdub", "Publish", "Collaborate"], pros: ["Creator focus", "Overdub", "Easy"], cons: ["Subscription", "Export"], website: "https://descript.com" }),

  // --- More per category (fulfill each) ---
  t({ id: "kobold-ai", name: "Kobold AI", description: "Open-source AI writing and roleplay. Run models locally or use cloud.", shortDescription: "Open AI writing and roleplay", category: "text-language", subcategory: "Chatbots", pricing: "free", priceRange: "Free", rating: 4.4, reviews: 12000, users: "500K+", tags: ["Writing", "Open", "Roleplay", "Local"], features: ["Local", "Cloud", "Models", "API"], pros: ["Free", "Private", "Custom"], cons: ["Tech", "Setup"], website: "https://koboldai.net" }),
  t({ id: "chatbase", name: "Chatbase", description: "Build AI chatbots from your data. Train on docs, site, or knowledge base.", shortDescription: "AI chatbots from your data", category: "text-language", subcategory: "Chatbots", pricing: "freemium", priceRange: "Free / $19-399/mo", rating: 4.5, reviews: 8000, users: "100K+", tags: ["Chatbot", "Custom", "Data", "Embed"], features: ["Train", "Embed", "API", "Widget"], pros: ["Easy", "Custom", "Embed"], cons: ["Limits", "Quality"], website: "https://chatbase.co" }),
  t({ id: "textcortex", name: "TextCortex", description: "AI writing for teams. 60+ use cases, integrations, and API.", shortDescription: "AI writing for teams", category: "text-language", subcategory: "Content Writing", pricing: "freemium", priceRange: "Free / $9-49/mo", rating: 4.4, reviews: 6000, users: "200K+", tags: ["Writing", "Teams", "API", "Integrations"], features: ["60+ Use cases", "Chrome", "API", "Templates"], pros: ["Integrations", "API", "Affordable"], cons: ["Quality varies", "Support"], website: "https://textcortex.com" }),
  t({ id: "neuroflash", name: "Neuroflash", description: "AI copywriting in 25+ languages. Ads, social, and long-form.", shortDescription: "AI copywriting 25+ languages", category: "text-language", subcategory: "Copywriting", pricing: "freemium", priceRange: "Free / $30-200/mo", rating: 4.4, reviews: 4000, users: "80K+", tags: ["Copy", "Multilingual", "Ads", "Social"], features: ["25+ Lang", "Templates", "Brand", "API"], pros: ["Languages", "Templates", "Good UX"], cons: ["Output varies", "Pricing"], website: "https://neuroflash.com" }),
  t({ id: "allora", name: "Allora", description: "AI image generation and design. Apps, API, and custom models.", shortDescription: "AI image and design", category: "image-design", subcategory: "Image Generation", pricing: "pay-per-use", priceRange: "Credits", rating: 4.5, reviews: 5000, users: "150K+", tags: ["Images", "API", "Design", "Custom"], features: ["Generation", "API", "Edit", "Styles"], pros: ["API", "Flexible", "Quality"], cons: ["Credits", "Docs"], website: "https://allora.ai" }),
  t({ id: "recraft", name: "Recraft", description: "AI graphic design. Icons, illustrations, and vectors from text.", shortDescription: "AI graphic design", category: "image-design", subcategory: "Image Generation", pricing: "freemium", priceRange: "Free / $18-96/mo", rating: 4.5, reviews: 4000, users: "100K+", tags: ["Design", "Vector", "Icons", "Illustration"], features: ["Vector", "Icons", "Edit", "Style"], pros: ["Vector", "Icons", "Quality"], cons: ["Niche", "Pricing"], website: "https://recraft.ai" }),
  t({ id: "krea", name: "Krea", description: "AI image generation and real-time canvas. Create and iterate fast.", shortDescription: "AI image and real-time canvas", category: "image-design", subcategory: "Image Generation", pricing: "freemium", priceRange: "Free / $12-48/mo", rating: 4.5, reviews: 6000, users: "200K+", tags: ["Images", "Canvas", "Real-time", "Design"], features: ["Real-time", "Canvas", "Upscale", "API"], pros: ["Fast", "Canvas", "Iterate"], cons: ["Credits", "Learning"], website: "https://krea.ai" }),
  t({ id: "kaiber", name: "Kaiber", description: "AI video and music visuals. Create clips from text or image with style control.", shortDescription: "AI video and music visuals", category: "video-audio", subcategory: "Video Generation", pricing: "freemium", priceRange: "Free / $5-30/mo", rating: 4.5, reviews: 8000, users: "300K+", tags: ["Video", "Music", "Visuals", "AI"], features: ["Text to Video", "Image to Video", "Music", "Styles"], pros: ["Music focus", "Styles", "Easy"], cons: ["Limits", "Pricing"], website: "https://kaiber.ai" }),
  t({ id: "verb-ai", name: "Verb", description: "AI video creation. Script to video with avatars and voiceovers.", shortDescription: "AI video from script", category: "video-audio", subcategory: "Video Generation", pricing: "subscription", priceRange: "$20-60/mo", rating: 4.4, reviews: 2000, users: "50K+", tags: ["Video", "Script", "Avatar", "Voice"], features: ["Script to Video", "Avatars", "Voice", "Templates"], pros: ["Easy", "Script focus", "Templates"], cons: ["Limits", "Quality"], website: "https://verb.ai" }),
  t({ id: "blackbox", name: "Blackbox", description: "AI code search and autocomplete. Find code, get suggestions, and chat.", shortDescription: "AI code search and complete", category: "code-developer", subcategory: "Code Generation", pricing: "freemium", priceRange: "Free / $10-20/mo", rating: 4.4, reviews: 15000, users: "1M+", tags: ["Code", "Search", "Complete", "Chat"], features: ["Search", "Complete", "Chat", "IDEs"], pros: ["Code search", "Free tier", "Fast"], cons: ["Quality varies", "Limits"], website: "https://blackbox.ai" }),
  t({ id: "codeium-api", name: "Codeium", description: "Free AI code completion. 70+ languages, 40+ IDEs.", shortDescription: "Free AI completion", category: "code-developer", subcategory: "Code Generation", pricing: "free", priceRange: "Free", rating: 4.5, reviews: 18000, users: "2.5M+", tags: ["Code", "Free", "Completion", "IDE"], features: ["Complete", "Chat", "70+ Lang", "40+ IDEs"], pros: ["Free", "No caps", "Good"], cons: ["Newer", "Models"], website: "https://codeium.com" }),
  t({ id: "outset", name: "Outset", description: "AI sales enablement. Calls, emails, and pipeline with AI insights.", shortDescription: "AI sales enablement", category: "business-marketing", subcategory: "Sales AI", pricing: "subscription", priceRange: "Custom", rating: 4.4, reviews: 1500, users: "40K+", tags: ["Sales", "Calls", "Enablement", "AI"], features: ["Calls", "Emails", "Insights", "Coaching"], pros: ["Sales focus", "Insights", "Integrate"], cons: ["Enterprise", "Cost"], website: "https://outset.ai" }),
  t({ id: "temporal", name: "Temporal", description: "AI workflow automation. Durable execution, workflows, and observability.", shortDescription: "AI workflow automation", category: "automation-agents", subcategory: "Workflow Automation", pricing: "freemium", priceRange: "Free / Custom", rating: 4.6, reviews: 5000, users: "100K+", tags: ["Workflow", "Automation", "Durable", "AI"], features: ["Durable", "Workflows", "Observability", "SDK"], pros: ["Reliable", "Scale", "Dev-friendly"], cons: ["Learning", "Self-host"], website: "https://temporal.io" }),
]
