import type { AITool } from "./data"

const logo = "/placeholder.svg"
type P = "free" | "freemium" | "subscription" | "pay-per-use" | "one-time" | "enterprise"

function u(o: {
  id: string
  name: string
  description: string
  shortDescription: string
  category: string
  subcategory: string
  pricing: P
  priceRange?: string
  rating: number
  reviews: number
  users: string
  tags: string[]
  features: string[]
  pros: string[]
  cons: string[]
  website: string
  verified?: boolean
  trending?: boolean
  new?: boolean
  featured?: boolean
}): AITool {
  return {
    ...o,
    logo,
    verified: o.verified ?? false,
    trending: o.trending ?? false,
    new: o.new ?? false,
    featured: o.featured ?? false,
  }
}

export const uncensoredTools: AITool[] = [
  u({
    id: "crushon",
    name: "CrushOn AI",
    description: "Unfiltered AI character chat with no content restrictions. Roleplay, adult conversations, and custom characters.",
    shortDescription: "Uncensored AI character chat",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "freemium",
    priceRange: "Free / $5-20/mo",
    rating: 4.5,
    reviews: 45000,
    users: "2M+",
    tags: ["Uncensored", "Chat", "Roleplay", "Adult"],
    features: ["No filters", "Custom characters", "NSFW", "Roleplay"],
    pros: ["Unfiltered", "Characters", "Active community"],
    cons: ["Premium for best", "Quality varies"],
    website: "https://www.crushon.ai",
    trending: true,
  }),
  u({
    id: "sakura-fm",
    name: "Sakura FM",
    description: "Uncensored AI chat and voice. Create characters, no content limits, adult-oriented conversations.",
    shortDescription: "Uncensored AI chat and voice",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "freemium",
    priceRange: "Free / $10-30/mo",
    rating: 4.4,
    reviews: 28000,
    users: "800K+",
    tags: ["Uncensored", "Voice", "Chat", "Adult"],
    features: ["No limits", "Voice", "Characters", "NSFW"],
    pros: ["Voice support", "Unfiltered", "Custom"],
    cons: ["Subscription", "App only"],
    website: "https://www.sakura.fm",
  }),
  u({
    id: "spicychat",
    name: "SpicyChat AI",
    description: "Unfiltered AI roleplay and chat. Adult content, custom bots, and no censorship.",
    shortDescription: "Uncensored AI roleplay",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "freemium",
    priceRange: "Free / $5-15/mo",
    rating: 4.4,
    reviews: 62000,
    users: "3M+",
    tags: ["Uncensored", "Roleplay", "Adult", "Bots"],
    features: ["No filters", "Custom bots", "NSFW", "Community"],
    pros: ["Free tier", "Active", "Variety"],
    cons: ["Queue times", "Quality varies"],
    website: "https://www.spicychat.ai",
    trending: true,
  }),
  u({
    id: "janitor-ai",
    name: "Janitor AI",
    description: "Uncensored AI chatbot platform. Create and chat with NSFW characters, no content restrictions.",
    shortDescription: "Uncensored AI chatbot platform",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "freemium",
    priceRange: "Free / API",
    rating: 4.3,
    reviews: 35000,
    users: "1M+",
    tags: ["Uncensored", "Chatbot", "NSFW", "API"],
    features: ["No limits", "API", "Custom bots", "Community"],
    pros: ["Flexible", "API", "Free tier"],
    cons: ["API setup", "Quality"],
    website: "https://www.janitorai.com",
  }),
  u({
    id: "seduced-ai",
    name: "Seduced AI",
    description: "Unfiltered AI companion chat. Adult-oriented conversations, roleplay, and no censorship.",
    shortDescription: "Uncensored AI companion",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "subscription",
    priceRange: "$10-25/mo",
    rating: 4.4,
    reviews: 12000,
    users: "300K+",
    tags: ["Uncensored", "Companion", "Adult", "Chat"],
    features: ["No filters", "Companion", "NSFW", "Private"],
    pros: ["Privacy", "Unfiltered", "Quality"],
    cons: ["Paid only", "Mobile focus"],
    website: "https://www.seduced.ai",
  }),
  u({
    id: "dreamgf",
    name: "DreamGF",
    description: "Uncensored AI girlfriend experience. Chat, images, and adult content with no restrictions.",
    shortDescription: "Uncensored AI girlfriend",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "subscription",
    priceRange: "$10-40/mo",
    rating: 4.3,
    reviews: 18000,
    users: "500K+",
    tags: ["Uncensored", "GF", "Adult", "Images"],
    features: ["Chat", "Images", "NSFW", "Custom"],
    pros: ["Immersive", "Images", "Unfiltered"],
    cons: ["Paid", "Niche"],
    website: "https://www.dreamgf.ai",
  }),
  u({
    id: "unstable-diffusion",
    name: "Unstable Diffusion",
    description: "Uncensored AI image generation. No content filters, adult imagery, and open community.",
    shortDescription: "Uncensored AI image generation",
    category: "uncensored",
    subcategory: "Image",
    pricing: "freemium",
    priceRange: "Free / $10-50/mo",
    rating: 4.4,
    reviews: 22000,
    users: "600K+",
    tags: ["Uncensored", "Images", "Adult", "Open"],
    features: ["No filters", "Models", "Community", "API"],
    pros: ["Open", "Unfiltered", "Custom models"],
    cons: ["Tech", "Self-host option"],
    website: "https://www.unstability.ai",
  }),
  u({
    id: "pornpen",
    name: "PornPen",
    description: "AI adult image generator. Uncensored imagery, multiple styles, and no content restrictions.",
    shortDescription: "Uncensored AI adult images",
    category: "uncensored",
    subcategory: "Image",
    pricing: "freemium",
    priceRange: "Free / $10-30/mo",
    rating: 4.3,
    reviews: 15000,
    users: "400K+",
    tags: ["Uncensored", "Images", "Adult", "Generator"],
    features: ["No filters", "Styles", "Custom", "Fast"],
    pros: ["Easy", "Unfiltered", "Variety"],
    cons: ["Credits", "Quality varies"],
    website: "https://pornpen.net/",
  }),
  u({
    id: "promptchan",
    name: "PromptChan",
    description: "Uncensored AI image generation. Anime and realistic adult imagery, no content limits.",
    shortDescription: "Uncensored AI image gen",
    category: "uncensored",
    subcategory: "Image",
    pricing: "freemium",
    priceRange: "Free / $8-25/mo",
    rating: 4.4,
    reviews: 12000,
    users: "350K+",
    tags: ["Uncensored", "Images", "Anime", "Adult"],
    features: ["No filters", "Anime", "Realistic", "LoRA"],
    pros: ["Anime focus", "Unfiltered", "Models"],
    cons: ["Credits", "Learning"],
    website: "https://promptchan.app/",
  }),
  u({
    id: "nsfw-ai",
    name: "NSFW AI",
    description: "Unfiltered AI image generator for adult content. Multiple models, no censorship.",
    shortDescription: "Uncensored adult image gen",
    category: "uncensored",
    subcategory: "Image",
    pricing: "pay-per-use",
    priceRange: "Credits",
    rating: 4.3,
    reviews: 8000,
    users: "200K+",
    tags: ["Uncensored", "Images", "NSFW", "Generator"],
    features: ["No filters", "Models", "API", "Custom"],
    pros: ["API", "Unfiltered", "Flexible"],
    cons: ["Credits", "Tech"],
    website: "https://www.kalon.ai/",
  }),
  u({
    id: "onlycharacters",
    name: "OnlyCharacters",
    description: "Uncensored AI character chat and roleplay. Adult content, custom personas, no filters.",
    shortDescription: "Uncensored character chat",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "subscription",
    priceRange: "$8-20/mo",
    rating: 4.4,
    reviews: 9000,
    users: "250K+",
    tags: ["Uncensored", "Characters", "Adult", "Roleplay"],
    features: ["No limits", "Characters", "NSFW", "Private"],
    pros: ["Privacy", "Unfiltered", "Variety"],
    cons: ["Paid", "Newer"],
    website: "https://www.onlycharacters.ai",
  }),
  u({
    id: "aicupid",
    name: "AI Cupid",
    description: "Uncensored AI dating and companion. Adult conversations, romantic roleplay, no restrictions.",
    shortDescription: "Uncensored AI dating",
    category: "uncensored",
    subcategory: "Chat",
    pricing: "freemium",
    priceRange: "Free / $12-35/mo",
    rating: 4.3,
    reviews: 11000,
    users: "400K+",
    tags: ["Uncensored", "Dating", "Adult", "Companion"],
    features: ["No filters", "Dating", "Roleplay", "Images"],
    pros: ["Immersive", "Unfiltered", "Features"],
    cons: ["Premium", "Niche"],
    website: "https://www.aicupid.org/",
  }),
]
